
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Newsletter
 * 
 */
export type Newsletter = Prisma.NewsletterModel
/**
 * Model Subscriber
 * Newsletter subscriber. Email is required; phone is optional and used for WhatsApp when whatsappOptIn is true.
 * Phone is unique when set so one number cannot be associated with multiple accounts.
 */
export type Subscriber = Prisma.SubscriberModel
/**
 * Model Schedule
 * 
 */
export type Schedule = Prisma.ScheduleModel
/**
 * Model EmailLog
 * 
 */
export type EmailLog = Prisma.EmailLogModel
/**
 * Model Tag
 * 
 */
export type Tag = Prisma.TagModel
/**
 * Model NewsletterTag
 * 
 */
export type NewsletterTag = Prisma.NewsletterTagModel
/**
 * Model PasswordResetToken
 * Time-limited token used for password reset emails.
 */
export type PasswordResetToken = Prisma.PasswordResetTokenModel
/**
 * Model Media
 * Uploaded media assets (images). Files are stored as base64 data URLs.
 */
export type Media = Prisma.MediaModel
