
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const NewsletterStatus = {
  draft: 'draft',
  scheduled: 'scheduled',
  published: 'published'
} as const

export type NewsletterStatus = (typeof NewsletterStatus)[keyof typeof NewsletterStatus]


export const SubscriberStatus = {
  active: 'active',
  unsubscribed: 'unsubscribed'
} as const

export type SubscriberStatus = (typeof SubscriberStatus)[keyof typeof SubscriberStatus]


export const ScheduleStatus = {
  pending: 'pending',
  sending: 'sending',
  sent: 'sent',
  failed: 'failed'
} as const

export type ScheduleStatus = (typeof ScheduleStatus)[keyof typeof ScheduleStatus]


export const EmailLogStatus = {
  pending: 'pending',
  sent: 'sent',
  delivered: 'delivered',
  opened: 'opened',
  clicked: 'clicked',
  failed: 'failed'
} as const

export type EmailLogStatus = (typeof EmailLogStatus)[keyof typeof EmailLogStatus]
