import Link from "next/link";

export const metadata = {
  title: "Terms of Service — GenContent AI",
  description: "Terms governing the use of GenContent AI.",
};

export default function TermsPage() {
  const updated = "March 16, 2026";

  return (
    <div className="min-h-screen bg-slate-950 text-slate-50">
      <header className="border-b border-slate-800 bg-slate-950/90 sticky top-0 z-10 backdrop-blur">
        <div className="mx-auto flex max-w-4xl items-center justify-between px-4 py-4">
          <Link href="/" className="text-lg font-bold bg-gradient-to-r from-sky-400 to-cyan-400 bg-clip-text text-transparent">
            GenContent AI
          </Link>
          <nav className="flex gap-4 text-sm text-slate-400">
            <Link href="/privacy" className="hover:text-slate-200">Privacy</Link>
            <Link href="/blog" className="hover:text-slate-200">Blog</Link>
          </nav>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-4 py-12">
        <h1 className="mb-2 text-3xl font-bold text-slate-50">Terms of Service</h1>
        <p className="mb-8 text-sm text-slate-500">Last updated: {updated}</p>

        <div className="prose prose-invert prose-sm max-w-none space-y-8 text-slate-300">
          <section>
            <h2 className="text-lg font-semibold text-slate-100">1. Acceptance</h2>
            <p>By using GenContent AI, you agree to these Terms of Service. If you do not agree, please do not use the service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-100">2. Use of the service</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>You must be 18 years or older to create an account.</li>
              <li>You are responsible for maintaining the security of your login credentials.</li>
              <li>You may not use the service for spam, illegal, or harmful content.</li>
              <li>You must comply with all applicable email marketing laws (CAN-SPAM, GDPR, CASL) when sending newsletters.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-100">3. Content</h2>
            <p>You retain ownership of all content you create. By using AI generation features, you accept that outputs are generated by third-party AI services (OpenAI, Google Gemini) and may require review before publication. GenContent AI is not responsible for AI-generated content inaccuracies.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-100">4. Email sending</h2>
            <p>You may only send newsletters to subscribers who have explicitly opted in to receive communications from you. You must honour unsubscribe requests promptly.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-100">5. Disclaimers</h2>
            <p>The service is provided &quot;as is&quot; without warranties of any kind. We do not guarantee uptime, availability, or accuracy of AI-generated content.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-100">6. Limitation of liability</h2>
            <p>To the maximum extent permitted by law, GenContent AI shall not be liable for any indirect, incidental, special, or consequential damages arising from use of the service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-100">7. Termination</h2>
            <p>We may suspend or terminate accounts that violate these terms. You may delete your account at any time.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-100">8. Changes</h2>
            <p>We may update these terms from time to time. Continued use of the service after changes constitutes acceptance.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-100">9. Contact</h2>
            <p>Questions? Email <a href="mailto:legal@gencontent.ai" className="text-cyan-400 hover:underline">legal@gencontent.ai</a></p>
          </section>
        </div>

        <div className="mt-10 border-t border-slate-800 pt-6 text-sm text-slate-500">
          <Link href="/privacy" className="hover:text-slate-300">Privacy Policy →</Link>
        </div>
      </main>

      <footer className="border-t border-slate-800 py-8 text-center text-sm text-slate-500">
        <p>© {new Date().getFullYear()} GenContent AI. All rights reserved.</p>
      </footer>
    </div>
  );
}
