import { render } from "@react-email/render";
import React from "react";
import { marked } from "marked";
import { NewsletterEmailTemplate } from "@/emails/NewsletterEmailTemplate";
import { BlogEmailTemplate } from "@/emails/BlogEmailTemplate";
import type { SendNewsletterEmailParams } from "./types";

// Base URL for links in emails (e.g. unsubscribe). Prefer APP_URL; neither should contain secrets.
const APP_URL =
  process.env.APP_URL ??
  process.env.NEXT_PUBLIC_APP_URL ??
  "http://localhost:3000";

// Optional logo URL for the email header (set BRAND_LOGO_URL in .env)
const BRAND_LOGO_URL = process.env.BRAND_LOGO_URL ?? undefined;
const BRAND_NAME = process.env.BRAND_NAME ?? "GenContent AI";

export function buildUnsubscribeUrl(subscriberId: string): string {
  return `${APP_URL.replace(/\/$/, "")}/api/unsubscribe?subscriberId=${encodeURIComponent(subscriberId)}`;
}

/**
 * Email clients (Gmail, Outlook, Apple Mail) do not render base64 data: URLs
 * in <img> tags. Only http:// and https:// URLs are safe to use.
 * Relative paths (e.g. /api/media/...) are converted to absolute URLs using APP_URL.
 * Returns undefined for data: URLs so the template simply omits the image.
 */
function safeEmailImageUrl(url: string | null | undefined): string | undefined {
  if (!url) return undefined;
  if (url.startsWith("data:")) return undefined;
  if (url.startsWith("http://") || url.startsWith("https://")) return url;
  // Convert relative paths like /api/media/... to absolute URLs
  if (url.startsWith("/")) return `${APP_URL.replace(/\/$/, "")}${url}`;
  return undefined;
}

/** Convert markdown to HTML for use in email body. */
async function markdownToHtml(markdown: string): Promise<string> {
  marked.setOptions({ breaks: true, gfm: true });
  const html = await marked.parse(markdown);
  return html;
}

/** Strip simple HTML tags for plain-text fallback (minimal). */
function stripHtml(html: string): string {
  return html
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/p>/gi, "\n")
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export interface RenderedNewsletter {
  html: string;
  text: string;
}

export async function renderNewsletterToHtml(
  params: SendNewsletterEmailParams,
  options?: { brand?: { name?: string; logoUrl?: string } },
): Promise<RenderedNewsletter> {
  const unsubscribeUrl = buildUnsubscribeUrl(params.subscriber.id);

  // Prefer per-newsletter logoUrl over the global BRAND_LOGO_URL env var
  const newsletterLogoUrl = safeEmailImageUrl(params.newsletter.logoUrl) ?? BRAND_LOGO_URL;
  const brand = options?.brand ?? {
    name: BRAND_NAME,
    logoUrl: newsletterLogoUrl,
  };

  const isBlog = params.newsletter.contentType === "blog";

  // Only use the banner image if it's a proper http/https URL.
  // Base64 data: URLs generated by Hugging Face are not supported by email clients.
  const safeBannerUrl = safeEmailImageUrl(params.newsletter.bannerImageUrl);
  const hasUnsupportedImage =
    !!params.newsletter.bannerImageUrl &&
    !safeBannerUrl;

  let bodyHtml = params.newsletter.body;
  const looksLikeHtml = /<[a-z][\s\S]*>/i.test(params.newsletter.body.trim());
  // Only convert to HTML if content is still Markdown (legacy). Tiptap-generated HTML is used as-is.
  if (!looksLikeHtml && (isBlog || /^#{1,6}\s|^\*\*|^\- |\n#{1,6}\s/m.test(params.newsletter.body))) {
    bodyHtml = await markdownToHtml(params.newsletter.body);
  }

  // When an AI-generated image (data URL) can't be embedded, prepend a note
  // so readers know an image exists and can view it in the content studio.
  if (hasUnsupportedImage) {
    const noteHtml =
      `<p style="background:#f3f4f6;border-left:4px solid #7c3aed;padding:10px 14px;border-radius:0 6px 6px 0;font-size:14px;color:#4b5563;margin:0 0 20px 0;">` +
      `📷 <strong>This post includes an AI-generated image.</strong> Open it in the content studio to view the full image.` +
      `</p>`;
    bodyHtml = noteHtml + bodyHtml;
  }

  let html: string;

  if (isBlog) {
    html = await render(
      React.createElement(BlogEmailTemplate, {
        blog: {
          subject: params.newsletter.subject,
          description: params.newsletter.description,
          body: bodyHtml,
          bannerImageUrl: safeBannerUrl,
          authorName: params.newsletter.authorName,
          publishedAt: params.newsletter.publishedAt
            ? String(params.newsletter.publishedAt)
            : undefined,
        },
        subscriber: {
          email: params.subscriber.email,
          name: params.subscriber.name,
        },
        unsubscribeUrl,
        brand,
      }),
    );
  } else {
    html = await render(
      React.createElement(NewsletterEmailTemplate, {
        newsletter: {
          subject: params.newsletter.subject,
          description: params.newsletter.description,
          body: bodyHtml,
          bannerImageUrl: safeBannerUrl,
        },
        subscriber: {
          email: params.subscriber.email,
          name: params.subscriber.name,
        },
        unsubscribeUrl,
        brand,
      }),
    );
  }

  const text = [
    params.newsletter.subject,
    params.newsletter.description ?? "",
    stripHtml(bodyHtml),
    "",
    `Unsubscribe: ${unsubscribeUrl}`,
  ]
    .filter(Boolean)
    .join("\n\n");

  return { html, text };
}
