
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EmailLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model EmailLog
 * 
 */
export type EmailLogModel = runtime.Types.Result.DefaultSelection<Prisma.$EmailLogPayload>

export type AggregateEmailLog = {
  _count: EmailLogCountAggregateOutputType | null
  _min: EmailLogMinAggregateOutputType | null
  _max: EmailLogMaxAggregateOutputType | null
}

export type EmailLogMinAggregateOutputType = {
  id: string | null
  newsletterId: string | null
  subscriberId: string | null
  provider: string | null
  providerMessageId: string | null
  status: $Enums.EmailLogStatus | null
  opened: boolean | null
  clicked: boolean | null
  deliveredAt: Date | null
  openedAt: Date | null
  clickedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type EmailLogMaxAggregateOutputType = {
  id: string | null
  newsletterId: string | null
  subscriberId: string | null
  provider: string | null
  providerMessageId: string | null
  status: $Enums.EmailLogStatus | null
  opened: boolean | null
  clicked: boolean | null
  deliveredAt: Date | null
  openedAt: Date | null
  clickedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type EmailLogCountAggregateOutputType = {
  id: number
  newsletterId: number
  subscriberId: number
  provider: number
  providerMessageId: number
  status: number
  opened: number
  clicked: number
  deliveredAt: number
  openedAt: number
  clickedAt: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  _all: number
}


export type EmailLogMinAggregateInputType = {
  id?: true
  newsletterId?: true
  subscriberId?: true
  provider?: true
  providerMessageId?: true
  status?: true
  opened?: true
  clicked?: true
  deliveredAt?: true
  openedAt?: true
  clickedAt?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type EmailLogMaxAggregateInputType = {
  id?: true
  newsletterId?: true
  subscriberId?: true
  provider?: true
  providerMessageId?: true
  status?: true
  opened?: true
  clicked?: true
  deliveredAt?: true
  openedAt?: true
  clickedAt?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type EmailLogCountAggregateInputType = {
  id?: true
  newsletterId?: true
  subscriberId?: true
  provider?: true
  providerMessageId?: true
  status?: true
  opened?: true
  clicked?: true
  deliveredAt?: true
  openedAt?: true
  clickedAt?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  _all?: true
}

export type EmailLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EmailLog to aggregate.
   */
  where?: Prisma.EmailLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmailLogs to fetch.
   */
  orderBy?: Prisma.EmailLogOrderByWithRelationInput | Prisma.EmailLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EmailLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmailLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmailLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EmailLogs
  **/
  _count?: true | EmailLogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EmailLogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EmailLogMaxAggregateInputType
}

export type GetEmailLogAggregateType<T extends EmailLogAggregateArgs> = {
      [P in keyof T & keyof AggregateEmailLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEmailLog[P]>
    : Prisma.GetScalarType<T[P], AggregateEmailLog[P]>
}




export type EmailLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmailLogWhereInput
  orderBy?: Prisma.EmailLogOrderByWithAggregationInput | Prisma.EmailLogOrderByWithAggregationInput[]
  by: Prisma.EmailLogScalarFieldEnum[] | Prisma.EmailLogScalarFieldEnum
  having?: Prisma.EmailLogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EmailLogCountAggregateInputType | true
  _min?: EmailLogMinAggregateInputType
  _max?: EmailLogMaxAggregateInputType
}

export type EmailLogGroupByOutputType = {
  id: string
  newsletterId: string
  subscriberId: string
  provider: string
  providerMessageId: string
  status: $Enums.EmailLogStatus
  opened: boolean
  clicked: boolean
  deliveredAt: Date | null
  openedAt: Date | null
  clickedAt: Date | null
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  _count: EmailLogCountAggregateOutputType | null
  _min: EmailLogMinAggregateOutputType | null
  _max: EmailLogMaxAggregateOutputType | null
}

type GetEmailLogGroupByPayload<T extends EmailLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EmailLogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EmailLogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EmailLogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EmailLogGroupByOutputType[P]>
      }
    >
  >



export type EmailLogWhereInput = {
  AND?: Prisma.EmailLogWhereInput | Prisma.EmailLogWhereInput[]
  OR?: Prisma.EmailLogWhereInput[]
  NOT?: Prisma.EmailLogWhereInput | Prisma.EmailLogWhereInput[]
  id?: Prisma.StringFilter<"EmailLog"> | string
  newsletterId?: Prisma.StringFilter<"EmailLog"> | string
  subscriberId?: Prisma.StringFilter<"EmailLog"> | string
  provider?: Prisma.StringFilter<"EmailLog"> | string
  providerMessageId?: Prisma.StringFilter<"EmailLog"> | string
  status?: Prisma.EnumEmailLogStatusFilter<"EmailLog"> | $Enums.EmailLogStatus
  opened?: Prisma.BoolFilter<"EmailLog"> | boolean
  clicked?: Prisma.BoolFilter<"EmailLog"> | boolean
  deliveredAt?: Prisma.DateTimeNullableFilter<"EmailLog"> | Date | string | null
  openedAt?: Prisma.DateTimeNullableFilter<"EmailLog"> | Date | string | null
  clickedAt?: Prisma.DateTimeNullableFilter<"EmailLog"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"EmailLog"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EmailLog"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"EmailLog"> | Date | string | null
  newsletter?: Prisma.XOR<Prisma.NewsletterScalarRelationFilter, Prisma.NewsletterWhereInput>
  subscriber?: Prisma.XOR<Prisma.SubscriberScalarRelationFilter, Prisma.SubscriberWhereInput>
}

export type EmailLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  newsletterId?: Prisma.SortOrder
  subscriberId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  providerMessageId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  opened?: Prisma.SortOrder
  clicked?: Prisma.SortOrder
  deliveredAt?: Prisma.SortOrderInput | Prisma.SortOrder
  openedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  clickedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  newsletter?: Prisma.NewsletterOrderByWithRelationInput
  subscriber?: Prisma.SubscriberOrderByWithRelationInput
}

export type EmailLogWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  provider_providerMessageId?: Prisma.EmailLogProviderProviderMessageIdCompoundUniqueInput
  AND?: Prisma.EmailLogWhereInput | Prisma.EmailLogWhereInput[]
  OR?: Prisma.EmailLogWhereInput[]
  NOT?: Prisma.EmailLogWhereInput | Prisma.EmailLogWhereInput[]
  newsletterId?: Prisma.StringFilter<"EmailLog"> | string
  subscriberId?: Prisma.StringFilter<"EmailLog"> | string
  provider?: Prisma.StringFilter<"EmailLog"> | string
  providerMessageId?: Prisma.StringFilter<"EmailLog"> | string
  status?: Prisma.EnumEmailLogStatusFilter<"EmailLog"> | $Enums.EmailLogStatus
  opened?: Prisma.BoolFilter<"EmailLog"> | boolean
  clicked?: Prisma.BoolFilter<"EmailLog"> | boolean
  deliveredAt?: Prisma.DateTimeNullableFilter<"EmailLog"> | Date | string | null
  openedAt?: Prisma.DateTimeNullableFilter<"EmailLog"> | Date | string | null
  clickedAt?: Prisma.DateTimeNullableFilter<"EmailLog"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"EmailLog"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EmailLog"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"EmailLog"> | Date | string | null
  newsletter?: Prisma.XOR<Prisma.NewsletterScalarRelationFilter, Prisma.NewsletterWhereInput>
  subscriber?: Prisma.XOR<Prisma.SubscriberScalarRelationFilter, Prisma.SubscriberWhereInput>
}, "id" | "provider_providerMessageId">

export type EmailLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  newsletterId?: Prisma.SortOrder
  subscriberId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  providerMessageId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  opened?: Prisma.SortOrder
  clicked?: Prisma.SortOrder
  deliveredAt?: Prisma.SortOrderInput | Prisma.SortOrder
  openedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  clickedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.EmailLogCountOrderByAggregateInput
  _max?: Prisma.EmailLogMaxOrderByAggregateInput
  _min?: Prisma.EmailLogMinOrderByAggregateInput
}

export type EmailLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.EmailLogScalarWhereWithAggregatesInput | Prisma.EmailLogScalarWhereWithAggregatesInput[]
  OR?: Prisma.EmailLogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EmailLogScalarWhereWithAggregatesInput | Prisma.EmailLogScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"EmailLog"> | string
  newsletterId?: Prisma.StringWithAggregatesFilter<"EmailLog"> | string
  subscriberId?: Prisma.StringWithAggregatesFilter<"EmailLog"> | string
  provider?: Prisma.StringWithAggregatesFilter<"EmailLog"> | string
  providerMessageId?: Prisma.StringWithAggregatesFilter<"EmailLog"> | string
  status?: Prisma.EnumEmailLogStatusWithAggregatesFilter<"EmailLog"> | $Enums.EmailLogStatus
  opened?: Prisma.BoolWithAggregatesFilter<"EmailLog"> | boolean
  clicked?: Prisma.BoolWithAggregatesFilter<"EmailLog"> | boolean
  deliveredAt?: Prisma.DateTimeNullableWithAggregatesFilter<"EmailLog"> | Date | string | null
  openedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"EmailLog"> | Date | string | null
  clickedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"EmailLog"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"EmailLog"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"EmailLog"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"EmailLog"> | Date | string | null
}

export type EmailLogCreateInput = {
  id?: string
  provider: string
  providerMessageId: string
  status?: $Enums.EmailLogStatus
  opened?: boolean
  clicked?: boolean
  deliveredAt?: Date | string | null
  openedAt?: Date | string | null
  clickedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  newsletter: Prisma.NewsletterCreateNestedOneWithoutEmailLogsInput
  subscriber: Prisma.SubscriberCreateNestedOneWithoutEmailLogsInput
}

export type EmailLogUncheckedCreateInput = {
  id?: string
  newsletterId: string
  subscriberId: string
  provider: string
  providerMessageId: string
  status?: $Enums.EmailLogStatus
  opened?: boolean
  clicked?: boolean
  deliveredAt?: Date | string | null
  openedAt?: Date | string | null
  clickedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type EmailLogUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  providerMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumEmailLogStatusFieldUpdateOperationsInput | $Enums.EmailLogStatus
  opened?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clicked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deliveredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  openedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  clickedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  newsletter?: Prisma.NewsletterUpdateOneRequiredWithoutEmailLogsNestedInput
  subscriber?: Prisma.SubscriberUpdateOneRequiredWithoutEmailLogsNestedInput
}

export type EmailLogUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  newsletterId?: Prisma.StringFieldUpdateOperationsInput | string
  subscriberId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  providerMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumEmailLogStatusFieldUpdateOperationsInput | $Enums.EmailLogStatus
  opened?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clicked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deliveredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  openedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  clickedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EmailLogCreateManyInput = {
  id?: string
  newsletterId: string
  subscriberId: string
  provider: string
  providerMessageId: string
  status?: $Enums.EmailLogStatus
  opened?: boolean
  clicked?: boolean
  deliveredAt?: Date | string | null
  openedAt?: Date | string | null
  clickedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type EmailLogUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  providerMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumEmailLogStatusFieldUpdateOperationsInput | $Enums.EmailLogStatus
  opened?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clicked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deliveredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  openedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  clickedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EmailLogUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  newsletterId?: Prisma.StringFieldUpdateOperationsInput | string
  subscriberId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  providerMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumEmailLogStatusFieldUpdateOperationsInput | $Enums.EmailLogStatus
  opened?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clicked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deliveredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  openedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  clickedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EmailLogListRelationFilter = {
  every?: Prisma.EmailLogWhereInput
  some?: Prisma.EmailLogWhereInput
  none?: Prisma.EmailLogWhereInput
}

export type EmailLogOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EmailLogProviderProviderMessageIdCompoundUniqueInput = {
  provider: string
  providerMessageId: string
}

export type EmailLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  newsletterId?: Prisma.SortOrder
  subscriberId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  providerMessageId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  opened?: Prisma.SortOrder
  clicked?: Prisma.SortOrder
  deliveredAt?: Prisma.SortOrder
  openedAt?: Prisma.SortOrder
  clickedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type EmailLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  newsletterId?: Prisma.SortOrder
  subscriberId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  providerMessageId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  opened?: Prisma.SortOrder
  clicked?: Prisma.SortOrder
  deliveredAt?: Prisma.SortOrder
  openedAt?: Prisma.SortOrder
  clickedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type EmailLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  newsletterId?: Prisma.SortOrder
  subscriberId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  providerMessageId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  opened?: Prisma.SortOrder
  clicked?: Prisma.SortOrder
  deliveredAt?: Prisma.SortOrder
  openedAt?: Prisma.SortOrder
  clickedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type EmailLogCreateNestedManyWithoutNewsletterInput = {
  create?: Prisma.XOR<Prisma.EmailLogCreateWithoutNewsletterInput, Prisma.EmailLogUncheckedCreateWithoutNewsletterInput> | Prisma.EmailLogCreateWithoutNewsletterInput[] | Prisma.EmailLogUncheckedCreateWithoutNewsletterInput[]
  connectOrCreate?: Prisma.EmailLogCreateOrConnectWithoutNewsletterInput | Prisma.EmailLogCreateOrConnectWithoutNewsletterInput[]
  createMany?: Prisma.EmailLogCreateManyNewsletterInputEnvelope
  connect?: Prisma.EmailLogWhereUniqueInput | Prisma.EmailLogWhereUniqueInput[]
}

export type EmailLogUncheckedCreateNestedManyWithoutNewsletterInput = {
  create?: Prisma.XOR<Prisma.EmailLogCreateWithoutNewsletterInput, Prisma.EmailLogUncheckedCreateWithoutNewsletterInput> | Prisma.EmailLogCreateWithoutNewsletterInput[] | Prisma.EmailLogUncheckedCreateWithoutNewsletterInput[]
  connectOrCreate?: Prisma.EmailLogCreateOrConnectWithoutNewsletterInput | Prisma.EmailLogCreateOrConnectWithoutNewsletterInput[]
  createMany?: Prisma.EmailLogCreateManyNewsletterInputEnvelope
  connect?: Prisma.EmailLogWhereUniqueInput | Prisma.EmailLogWhereUniqueInput[]
}

export type EmailLogUpdateManyWithoutNewsletterNestedInput = {
  create?: Prisma.XOR<Prisma.EmailLogCreateWithoutNewsletterInput, Prisma.EmailLogUncheckedCreateWithoutNewsletterInput> | Prisma.EmailLogCreateWithoutNewsletterInput[] | Prisma.EmailLogUncheckedCreateWithoutNewsletterInput[]
  connectOrCreate?: Prisma.EmailLogCreateOrConnectWithoutNewsletterInput | Prisma.EmailLogCreateOrConnectWithoutNewsletterInput[]
  upsert?: Prisma.EmailLogUpsertWithWhereUniqueWithoutNewsletterInput | Prisma.EmailLogUpsertWithWhereUniqueWithoutNewsletterInput[]
  createMany?: Prisma.EmailLogCreateManyNewsletterInputEnvelope
  set?: Prisma.EmailLogWhereUniqueInput | Prisma.EmailLogWhereUniqueInput[]
  disconnect?: Prisma.EmailLogWhereUniqueInput | Prisma.EmailLogWhereUniqueInput[]
  delete?: Prisma.EmailLogWhereUniqueInput | Prisma.EmailLogWhereUniqueInput[]
  connect?: Prisma.EmailLogWhereUniqueInput | Prisma.EmailLogWhereUniqueInput[]
  update?: Prisma.EmailLogUpdateWithWhereUniqueWithoutNewsletterInput | Prisma.EmailLogUpdateWithWhereUniqueWithoutNewsletterInput[]
  updateMany?: Prisma.EmailLogUpdateManyWithWhereWithoutNewsletterInput | Prisma.EmailLogUpdateManyWithWhereWithoutNewsletterInput[]
  deleteMany?: Prisma.EmailLogScalarWhereInput | Prisma.EmailLogScalarWhereInput[]
}

export type EmailLogUncheckedUpdateManyWithoutNewsletterNestedInput = {
  create?: Prisma.XOR<Prisma.EmailLogCreateWithoutNewsletterInput, Prisma.EmailLogUncheckedCreateWithoutNewsletterInput> | Prisma.EmailLogCreateWithoutNewsletterInput[] | Prisma.EmailLogUncheckedCreateWithoutNewsletterInput[]
  connectOrCreate?: Prisma.EmailLogCreateOrConnectWithoutNewsletterInput | Prisma.EmailLogCreateOrConnectWithoutNewsletterInput[]
  upsert?: Prisma.EmailLogUpsertWithWhereUniqueWithoutNewsletterInput | Prisma.EmailLogUpsertWithWhereUniqueWithoutNewsletterInput[]
  createMany?: Prisma.EmailLogCreateManyNewsletterInputEnvelope
  set?: Prisma.EmailLogWhereUniqueInput | Prisma.EmailLogWhereUniqueInput[]
  disconnect?: Prisma.EmailLogWhereUniqueInput | Prisma.EmailLogWhereUniqueInput[]
  delete?: Prisma.EmailLogWhereUniqueInput | Prisma.EmailLogWhereUniqueInput[]
  connect?: Prisma.EmailLogWhereUniqueInput | Prisma.EmailLogWhereUniqueInput[]
  update?: Prisma.EmailLogUpdateWithWhereUniqueWithoutNewsletterInput | Prisma.EmailLogUpdateWithWhereUniqueWithoutNewsletterInput[]
  updateMany?: Prisma.EmailLogUpdateManyWithWhereWithoutNewsletterInput | Prisma.EmailLogUpdateManyWithWhereWithoutNewsletterInput[]
  deleteMany?: Prisma.EmailLogScalarWhereInput | Prisma.EmailLogScalarWhereInput[]
}

export type EmailLogCreateNestedManyWithoutSubscriberInput = {
  create?: Prisma.XOR<Prisma.EmailLogCreateWithoutSubscriberInput, Prisma.EmailLogUncheckedCreateWithoutSubscriberInput> | Prisma.EmailLogCreateWithoutSubscriberInput[] | Prisma.EmailLogUncheckedCreateWithoutSubscriberInput[]
  connectOrCreate?: Prisma.EmailLogCreateOrConnectWithoutSubscriberInput | Prisma.EmailLogCreateOrConnectWithoutSubscriberInput[]
  createMany?: Prisma.EmailLogCreateManySubscriberInputEnvelope
  connect?: Prisma.EmailLogWhereUniqueInput | Prisma.EmailLogWhereUniqueInput[]
}

export type EmailLogUncheckedCreateNestedManyWithoutSubscriberInput = {
  create?: Prisma.XOR<Prisma.EmailLogCreateWithoutSubscriberInput, Prisma.EmailLogUncheckedCreateWithoutSubscriberInput> | Prisma.EmailLogCreateWithoutSubscriberInput[] | Prisma.EmailLogUncheckedCreateWithoutSubscriberInput[]
  connectOrCreate?: Prisma.EmailLogCreateOrConnectWithoutSubscriberInput | Prisma.EmailLogCreateOrConnectWithoutSubscriberInput[]
  createMany?: Prisma.EmailLogCreateManySubscriberInputEnvelope
  connect?: Prisma.EmailLogWhereUniqueInput | Prisma.EmailLogWhereUniqueInput[]
}

export type EmailLogUpdateManyWithoutSubscriberNestedInput = {
  create?: Prisma.XOR<Prisma.EmailLogCreateWithoutSubscriberInput, Prisma.EmailLogUncheckedCreateWithoutSubscriberInput> | Prisma.EmailLogCreateWithoutSubscriberInput[] | Prisma.EmailLogUncheckedCreateWithoutSubscriberInput[]
  connectOrCreate?: Prisma.EmailLogCreateOrConnectWithoutSubscriberInput | Prisma.EmailLogCreateOrConnectWithoutSubscriberInput[]
  upsert?: Prisma.EmailLogUpsertWithWhereUniqueWithoutSubscriberInput | Prisma.EmailLogUpsertWithWhereUniqueWithoutSubscriberInput[]
  createMany?: Prisma.EmailLogCreateManySubscriberInputEnvelope
  set?: Prisma.EmailLogWhereUniqueInput | Prisma.EmailLogWhereUniqueInput[]
  disconnect?: Prisma.EmailLogWhereUniqueInput | Prisma.EmailLogWhereUniqueInput[]
  delete?: Prisma.EmailLogWhereUniqueInput | Prisma.EmailLogWhereUniqueInput[]
  connect?: Prisma.EmailLogWhereUniqueInput | Prisma.EmailLogWhereUniqueInput[]
  update?: Prisma.EmailLogUpdateWithWhereUniqueWithoutSubscriberInput | Prisma.EmailLogUpdateWithWhereUniqueWithoutSubscriberInput[]
  updateMany?: Prisma.EmailLogUpdateManyWithWhereWithoutSubscriberInput | Prisma.EmailLogUpdateManyWithWhereWithoutSubscriberInput[]
  deleteMany?: Prisma.EmailLogScalarWhereInput | Prisma.EmailLogScalarWhereInput[]
}

export type EmailLogUncheckedUpdateManyWithoutSubscriberNestedInput = {
  create?: Prisma.XOR<Prisma.EmailLogCreateWithoutSubscriberInput, Prisma.EmailLogUncheckedCreateWithoutSubscriberInput> | Prisma.EmailLogCreateWithoutSubscriberInput[] | Prisma.EmailLogUncheckedCreateWithoutSubscriberInput[]
  connectOrCreate?: Prisma.EmailLogCreateOrConnectWithoutSubscriberInput | Prisma.EmailLogCreateOrConnectWithoutSubscriberInput[]
  upsert?: Prisma.EmailLogUpsertWithWhereUniqueWithoutSubscriberInput | Prisma.EmailLogUpsertWithWhereUniqueWithoutSubscriberInput[]
  createMany?: Prisma.EmailLogCreateManySubscriberInputEnvelope
  set?: Prisma.EmailLogWhereUniqueInput | Prisma.EmailLogWhereUniqueInput[]
  disconnect?: Prisma.EmailLogWhereUniqueInput | Prisma.EmailLogWhereUniqueInput[]
  delete?: Prisma.EmailLogWhereUniqueInput | Prisma.EmailLogWhereUniqueInput[]
  connect?: Prisma.EmailLogWhereUniqueInput | Prisma.EmailLogWhereUniqueInput[]
  update?: Prisma.EmailLogUpdateWithWhereUniqueWithoutSubscriberInput | Prisma.EmailLogUpdateWithWhereUniqueWithoutSubscriberInput[]
  updateMany?: Prisma.EmailLogUpdateManyWithWhereWithoutSubscriberInput | Prisma.EmailLogUpdateManyWithWhereWithoutSubscriberInput[]
  deleteMany?: Prisma.EmailLogScalarWhereInput | Prisma.EmailLogScalarWhereInput[]
}

export type EnumEmailLogStatusFieldUpdateOperationsInput = {
  set?: $Enums.EmailLogStatus
}

export type EmailLogCreateWithoutNewsletterInput = {
  id?: string
  provider: string
  providerMessageId: string
  status?: $Enums.EmailLogStatus
  opened?: boolean
  clicked?: boolean
  deliveredAt?: Date | string | null
  openedAt?: Date | string | null
  clickedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  subscriber: Prisma.SubscriberCreateNestedOneWithoutEmailLogsInput
}

export type EmailLogUncheckedCreateWithoutNewsletterInput = {
  id?: string
  subscriberId: string
  provider: string
  providerMessageId: string
  status?: $Enums.EmailLogStatus
  opened?: boolean
  clicked?: boolean
  deliveredAt?: Date | string | null
  openedAt?: Date | string | null
  clickedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type EmailLogCreateOrConnectWithoutNewsletterInput = {
  where: Prisma.EmailLogWhereUniqueInput
  create: Prisma.XOR<Prisma.EmailLogCreateWithoutNewsletterInput, Prisma.EmailLogUncheckedCreateWithoutNewsletterInput>
}

export type EmailLogCreateManyNewsletterInputEnvelope = {
  data: Prisma.EmailLogCreateManyNewsletterInput | Prisma.EmailLogCreateManyNewsletterInput[]
  skipDuplicates?: boolean
}

export type EmailLogUpsertWithWhereUniqueWithoutNewsletterInput = {
  where: Prisma.EmailLogWhereUniqueInput
  update: Prisma.XOR<Prisma.EmailLogUpdateWithoutNewsletterInput, Prisma.EmailLogUncheckedUpdateWithoutNewsletterInput>
  create: Prisma.XOR<Prisma.EmailLogCreateWithoutNewsletterInput, Prisma.EmailLogUncheckedCreateWithoutNewsletterInput>
}

export type EmailLogUpdateWithWhereUniqueWithoutNewsletterInput = {
  where: Prisma.EmailLogWhereUniqueInput
  data: Prisma.XOR<Prisma.EmailLogUpdateWithoutNewsletterInput, Prisma.EmailLogUncheckedUpdateWithoutNewsletterInput>
}

export type EmailLogUpdateManyWithWhereWithoutNewsletterInput = {
  where: Prisma.EmailLogScalarWhereInput
  data: Prisma.XOR<Prisma.EmailLogUpdateManyMutationInput, Prisma.EmailLogUncheckedUpdateManyWithoutNewsletterInput>
}

export type EmailLogScalarWhereInput = {
  AND?: Prisma.EmailLogScalarWhereInput | Prisma.EmailLogScalarWhereInput[]
  OR?: Prisma.EmailLogScalarWhereInput[]
  NOT?: Prisma.EmailLogScalarWhereInput | Prisma.EmailLogScalarWhereInput[]
  id?: Prisma.StringFilter<"EmailLog"> | string
  newsletterId?: Prisma.StringFilter<"EmailLog"> | string
  subscriberId?: Prisma.StringFilter<"EmailLog"> | string
  provider?: Prisma.StringFilter<"EmailLog"> | string
  providerMessageId?: Prisma.StringFilter<"EmailLog"> | string
  status?: Prisma.EnumEmailLogStatusFilter<"EmailLog"> | $Enums.EmailLogStatus
  opened?: Prisma.BoolFilter<"EmailLog"> | boolean
  clicked?: Prisma.BoolFilter<"EmailLog"> | boolean
  deliveredAt?: Prisma.DateTimeNullableFilter<"EmailLog"> | Date | string | null
  openedAt?: Prisma.DateTimeNullableFilter<"EmailLog"> | Date | string | null
  clickedAt?: Prisma.DateTimeNullableFilter<"EmailLog"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"EmailLog"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EmailLog"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"EmailLog"> | Date | string | null
}

export type EmailLogCreateWithoutSubscriberInput = {
  id?: string
  provider: string
  providerMessageId: string
  status?: $Enums.EmailLogStatus
  opened?: boolean
  clicked?: boolean
  deliveredAt?: Date | string | null
  openedAt?: Date | string | null
  clickedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  newsletter: Prisma.NewsletterCreateNestedOneWithoutEmailLogsInput
}

export type EmailLogUncheckedCreateWithoutSubscriberInput = {
  id?: string
  newsletterId: string
  provider: string
  providerMessageId: string
  status?: $Enums.EmailLogStatus
  opened?: boolean
  clicked?: boolean
  deliveredAt?: Date | string | null
  openedAt?: Date | string | null
  clickedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type EmailLogCreateOrConnectWithoutSubscriberInput = {
  where: Prisma.EmailLogWhereUniqueInput
  create: Prisma.XOR<Prisma.EmailLogCreateWithoutSubscriberInput, Prisma.EmailLogUncheckedCreateWithoutSubscriberInput>
}

export type EmailLogCreateManySubscriberInputEnvelope = {
  data: Prisma.EmailLogCreateManySubscriberInput | Prisma.EmailLogCreateManySubscriberInput[]
  skipDuplicates?: boolean
}

export type EmailLogUpsertWithWhereUniqueWithoutSubscriberInput = {
  where: Prisma.EmailLogWhereUniqueInput
  update: Prisma.XOR<Prisma.EmailLogUpdateWithoutSubscriberInput, Prisma.EmailLogUncheckedUpdateWithoutSubscriberInput>
  create: Prisma.XOR<Prisma.EmailLogCreateWithoutSubscriberInput, Prisma.EmailLogUncheckedCreateWithoutSubscriberInput>
}

export type EmailLogUpdateWithWhereUniqueWithoutSubscriberInput = {
  where: Prisma.EmailLogWhereUniqueInput
  data: Prisma.XOR<Prisma.EmailLogUpdateWithoutSubscriberInput, Prisma.EmailLogUncheckedUpdateWithoutSubscriberInput>
}

export type EmailLogUpdateManyWithWhereWithoutSubscriberInput = {
  where: Prisma.EmailLogScalarWhereInput
  data: Prisma.XOR<Prisma.EmailLogUpdateManyMutationInput, Prisma.EmailLogUncheckedUpdateManyWithoutSubscriberInput>
}

export type EmailLogCreateManyNewsletterInput = {
  id?: string
  subscriberId: string
  provider: string
  providerMessageId: string
  status?: $Enums.EmailLogStatus
  opened?: boolean
  clicked?: boolean
  deliveredAt?: Date | string | null
  openedAt?: Date | string | null
  clickedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type EmailLogUpdateWithoutNewsletterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  providerMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumEmailLogStatusFieldUpdateOperationsInput | $Enums.EmailLogStatus
  opened?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clicked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deliveredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  openedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  clickedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  subscriber?: Prisma.SubscriberUpdateOneRequiredWithoutEmailLogsNestedInput
}

export type EmailLogUncheckedUpdateWithoutNewsletterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  subscriberId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  providerMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumEmailLogStatusFieldUpdateOperationsInput | $Enums.EmailLogStatus
  opened?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clicked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deliveredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  openedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  clickedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EmailLogUncheckedUpdateManyWithoutNewsletterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  subscriberId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  providerMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumEmailLogStatusFieldUpdateOperationsInput | $Enums.EmailLogStatus
  opened?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clicked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deliveredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  openedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  clickedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EmailLogCreateManySubscriberInput = {
  id?: string
  newsletterId: string
  provider: string
  providerMessageId: string
  status?: $Enums.EmailLogStatus
  opened?: boolean
  clicked?: boolean
  deliveredAt?: Date | string | null
  openedAt?: Date | string | null
  clickedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type EmailLogUpdateWithoutSubscriberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  providerMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumEmailLogStatusFieldUpdateOperationsInput | $Enums.EmailLogStatus
  opened?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clicked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deliveredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  openedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  clickedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  newsletter?: Prisma.NewsletterUpdateOneRequiredWithoutEmailLogsNestedInput
}

export type EmailLogUncheckedUpdateWithoutSubscriberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  newsletterId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  providerMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumEmailLogStatusFieldUpdateOperationsInput | $Enums.EmailLogStatus
  opened?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clicked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deliveredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  openedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  clickedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EmailLogUncheckedUpdateManyWithoutSubscriberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  newsletterId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  providerMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumEmailLogStatusFieldUpdateOperationsInput | $Enums.EmailLogStatus
  opened?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clicked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deliveredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  openedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  clickedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type EmailLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  newsletterId?: boolean
  subscriberId?: boolean
  provider?: boolean
  providerMessageId?: boolean
  status?: boolean
  opened?: boolean
  clicked?: boolean
  deliveredAt?: boolean
  openedAt?: boolean
  clickedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  newsletter?: boolean | Prisma.NewsletterDefaultArgs<ExtArgs>
  subscriber?: boolean | Prisma.SubscriberDefaultArgs<ExtArgs>
}, ExtArgs["result"]["emailLog"]>

export type EmailLogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  newsletterId?: boolean
  subscriberId?: boolean
  provider?: boolean
  providerMessageId?: boolean
  status?: boolean
  opened?: boolean
  clicked?: boolean
  deliveredAt?: boolean
  openedAt?: boolean
  clickedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  newsletter?: boolean | Prisma.NewsletterDefaultArgs<ExtArgs>
  subscriber?: boolean | Prisma.SubscriberDefaultArgs<ExtArgs>
}, ExtArgs["result"]["emailLog"]>

export type EmailLogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  newsletterId?: boolean
  subscriberId?: boolean
  provider?: boolean
  providerMessageId?: boolean
  status?: boolean
  opened?: boolean
  clicked?: boolean
  deliveredAt?: boolean
  openedAt?: boolean
  clickedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  newsletter?: boolean | Prisma.NewsletterDefaultArgs<ExtArgs>
  subscriber?: boolean | Prisma.SubscriberDefaultArgs<ExtArgs>
}, ExtArgs["result"]["emailLog"]>

export type EmailLogSelectScalar = {
  id?: boolean
  newsletterId?: boolean
  subscriberId?: boolean
  provider?: boolean
  providerMessageId?: boolean
  status?: boolean
  opened?: boolean
  clicked?: boolean
  deliveredAt?: boolean
  openedAt?: boolean
  clickedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}

export type EmailLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "newsletterId" | "subscriberId" | "provider" | "providerMessageId" | "status" | "opened" | "clicked" | "deliveredAt" | "openedAt" | "clickedAt" | "createdAt" | "updatedAt" | "deletedAt", ExtArgs["result"]["emailLog"]>
export type EmailLogInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  newsletter?: boolean | Prisma.NewsletterDefaultArgs<ExtArgs>
  subscriber?: boolean | Prisma.SubscriberDefaultArgs<ExtArgs>
}
export type EmailLogIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  newsletter?: boolean | Prisma.NewsletterDefaultArgs<ExtArgs>
  subscriber?: boolean | Prisma.SubscriberDefaultArgs<ExtArgs>
}
export type EmailLogIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  newsletter?: boolean | Prisma.NewsletterDefaultArgs<ExtArgs>
  subscriber?: boolean | Prisma.SubscriberDefaultArgs<ExtArgs>
}

export type $EmailLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EmailLog"
  objects: {
    newsletter: Prisma.$NewsletterPayload<ExtArgs>
    subscriber: Prisma.$SubscriberPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    newsletterId: string
    subscriberId: string
    provider: string
    providerMessageId: string
    status: $Enums.EmailLogStatus
    opened: boolean
    clicked: boolean
    deliveredAt: Date | null
    openedAt: Date | null
    clickedAt: Date | null
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
  }, ExtArgs["result"]["emailLog"]>
  composites: {}
}

export type EmailLogGetPayload<S extends boolean | null | undefined | EmailLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EmailLogPayload, S>

export type EmailLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EmailLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EmailLogCountAggregateInputType | true
  }

export interface EmailLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EmailLog'], meta: { name: 'EmailLog' } }
  /**
   * Find zero or one EmailLog that matches the filter.
   * @param {EmailLogFindUniqueArgs} args - Arguments to find a EmailLog
   * @example
   * // Get one EmailLog
   * const emailLog = await prisma.emailLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EmailLogFindUniqueArgs>(args: Prisma.SelectSubset<T, EmailLogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EmailLogClient<runtime.Types.Result.GetResult<Prisma.$EmailLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EmailLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EmailLogFindUniqueOrThrowArgs} args - Arguments to find a EmailLog
   * @example
   * // Get one EmailLog
   * const emailLog = await prisma.emailLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EmailLogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EmailLogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmailLogClient<runtime.Types.Result.GetResult<Prisma.$EmailLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EmailLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailLogFindFirstArgs} args - Arguments to find a EmailLog
   * @example
   * // Get one EmailLog
   * const emailLog = await prisma.emailLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EmailLogFindFirstArgs>(args?: Prisma.SelectSubset<T, EmailLogFindFirstArgs<ExtArgs>>): Prisma.Prisma__EmailLogClient<runtime.Types.Result.GetResult<Prisma.$EmailLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EmailLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailLogFindFirstOrThrowArgs} args - Arguments to find a EmailLog
   * @example
   * // Get one EmailLog
   * const emailLog = await prisma.emailLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EmailLogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EmailLogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmailLogClient<runtime.Types.Result.GetResult<Prisma.$EmailLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EmailLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EmailLogs
   * const emailLogs = await prisma.emailLog.findMany()
   * 
   * // Get first 10 EmailLogs
   * const emailLogs = await prisma.emailLog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const emailLogWithIdOnly = await prisma.emailLog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EmailLogFindManyArgs>(args?: Prisma.SelectSubset<T, EmailLogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmailLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EmailLog.
   * @param {EmailLogCreateArgs} args - Arguments to create a EmailLog.
   * @example
   * // Create one EmailLog
   * const EmailLog = await prisma.emailLog.create({
   *   data: {
   *     // ... data to create a EmailLog
   *   }
   * })
   * 
   */
  create<T extends EmailLogCreateArgs>(args: Prisma.SelectSubset<T, EmailLogCreateArgs<ExtArgs>>): Prisma.Prisma__EmailLogClient<runtime.Types.Result.GetResult<Prisma.$EmailLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EmailLogs.
   * @param {EmailLogCreateManyArgs} args - Arguments to create many EmailLogs.
   * @example
   * // Create many EmailLogs
   * const emailLog = await prisma.emailLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EmailLogCreateManyArgs>(args?: Prisma.SelectSubset<T, EmailLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EmailLogs and returns the data saved in the database.
   * @param {EmailLogCreateManyAndReturnArgs} args - Arguments to create many EmailLogs.
   * @example
   * // Create many EmailLogs
   * const emailLog = await prisma.emailLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EmailLogs and only return the `id`
   * const emailLogWithIdOnly = await prisma.emailLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EmailLogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EmailLogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmailLogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EmailLog.
   * @param {EmailLogDeleteArgs} args - Arguments to delete one EmailLog.
   * @example
   * // Delete one EmailLog
   * const EmailLog = await prisma.emailLog.delete({
   *   where: {
   *     // ... filter to delete one EmailLog
   *   }
   * })
   * 
   */
  delete<T extends EmailLogDeleteArgs>(args: Prisma.SelectSubset<T, EmailLogDeleteArgs<ExtArgs>>): Prisma.Prisma__EmailLogClient<runtime.Types.Result.GetResult<Prisma.$EmailLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EmailLog.
   * @param {EmailLogUpdateArgs} args - Arguments to update one EmailLog.
   * @example
   * // Update one EmailLog
   * const emailLog = await prisma.emailLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EmailLogUpdateArgs>(args: Prisma.SelectSubset<T, EmailLogUpdateArgs<ExtArgs>>): Prisma.Prisma__EmailLogClient<runtime.Types.Result.GetResult<Prisma.$EmailLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EmailLogs.
   * @param {EmailLogDeleteManyArgs} args - Arguments to filter EmailLogs to delete.
   * @example
   * // Delete a few EmailLogs
   * const { count } = await prisma.emailLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EmailLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, EmailLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EmailLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EmailLogs
   * const emailLog = await prisma.emailLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EmailLogUpdateManyArgs>(args: Prisma.SelectSubset<T, EmailLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EmailLogs and returns the data updated in the database.
   * @param {EmailLogUpdateManyAndReturnArgs} args - Arguments to update many EmailLogs.
   * @example
   * // Update many EmailLogs
   * const emailLog = await prisma.emailLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EmailLogs and only return the `id`
   * const emailLogWithIdOnly = await prisma.emailLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EmailLogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EmailLogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmailLogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EmailLog.
   * @param {EmailLogUpsertArgs} args - Arguments to update or create a EmailLog.
   * @example
   * // Update or create a EmailLog
   * const emailLog = await prisma.emailLog.upsert({
   *   create: {
   *     // ... data to create a EmailLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EmailLog we want to update
   *   }
   * })
   */
  upsert<T extends EmailLogUpsertArgs>(args: Prisma.SelectSubset<T, EmailLogUpsertArgs<ExtArgs>>): Prisma.Prisma__EmailLogClient<runtime.Types.Result.GetResult<Prisma.$EmailLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EmailLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailLogCountArgs} args - Arguments to filter EmailLogs to count.
   * @example
   * // Count the number of EmailLogs
   * const count = await prisma.emailLog.count({
   *   where: {
   *     // ... the filter for the EmailLogs we want to count
   *   }
   * })
  **/
  count<T extends EmailLogCountArgs>(
    args?: Prisma.Subset<T, EmailLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EmailLogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EmailLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EmailLogAggregateArgs>(args: Prisma.Subset<T, EmailLogAggregateArgs>): Prisma.PrismaPromise<GetEmailLogAggregateType<T>>

  /**
   * Group by EmailLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EmailLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EmailLogGroupByArgs['orderBy'] }
      : { orderBy?: EmailLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EmailLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEmailLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EmailLog model
 */
readonly fields: EmailLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EmailLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EmailLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  newsletter<T extends Prisma.NewsletterDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.NewsletterDefaultArgs<ExtArgs>>): Prisma.Prisma__NewsletterClient<runtime.Types.Result.GetResult<Prisma.$NewsletterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  subscriber<T extends Prisma.SubscriberDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SubscriberDefaultArgs<ExtArgs>>): Prisma.Prisma__SubscriberClient<runtime.Types.Result.GetResult<Prisma.$SubscriberPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EmailLog model
 */
export interface EmailLogFieldRefs {
  readonly id: Prisma.FieldRef<"EmailLog", 'String'>
  readonly newsletterId: Prisma.FieldRef<"EmailLog", 'String'>
  readonly subscriberId: Prisma.FieldRef<"EmailLog", 'String'>
  readonly provider: Prisma.FieldRef<"EmailLog", 'String'>
  readonly providerMessageId: Prisma.FieldRef<"EmailLog", 'String'>
  readonly status: Prisma.FieldRef<"EmailLog", 'EmailLogStatus'>
  readonly opened: Prisma.FieldRef<"EmailLog", 'Boolean'>
  readonly clicked: Prisma.FieldRef<"EmailLog", 'Boolean'>
  readonly deliveredAt: Prisma.FieldRef<"EmailLog", 'DateTime'>
  readonly openedAt: Prisma.FieldRef<"EmailLog", 'DateTime'>
  readonly clickedAt: Prisma.FieldRef<"EmailLog", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"EmailLog", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"EmailLog", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"EmailLog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * EmailLog findUnique
 */
export type EmailLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailLog
   */
  select?: Prisma.EmailLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailLog
   */
  omit?: Prisma.EmailLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailLogInclude<ExtArgs> | null
  /**
   * Filter, which EmailLog to fetch.
   */
  where: Prisma.EmailLogWhereUniqueInput
}

/**
 * EmailLog findUniqueOrThrow
 */
export type EmailLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailLog
   */
  select?: Prisma.EmailLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailLog
   */
  omit?: Prisma.EmailLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailLogInclude<ExtArgs> | null
  /**
   * Filter, which EmailLog to fetch.
   */
  where: Prisma.EmailLogWhereUniqueInput
}

/**
 * EmailLog findFirst
 */
export type EmailLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailLog
   */
  select?: Prisma.EmailLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailLog
   */
  omit?: Prisma.EmailLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailLogInclude<ExtArgs> | null
  /**
   * Filter, which EmailLog to fetch.
   */
  where?: Prisma.EmailLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmailLogs to fetch.
   */
  orderBy?: Prisma.EmailLogOrderByWithRelationInput | Prisma.EmailLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EmailLogs.
   */
  cursor?: Prisma.EmailLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmailLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmailLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EmailLogs.
   */
  distinct?: Prisma.EmailLogScalarFieldEnum | Prisma.EmailLogScalarFieldEnum[]
}

/**
 * EmailLog findFirstOrThrow
 */
export type EmailLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailLog
   */
  select?: Prisma.EmailLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailLog
   */
  omit?: Prisma.EmailLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailLogInclude<ExtArgs> | null
  /**
   * Filter, which EmailLog to fetch.
   */
  where?: Prisma.EmailLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmailLogs to fetch.
   */
  orderBy?: Prisma.EmailLogOrderByWithRelationInput | Prisma.EmailLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EmailLogs.
   */
  cursor?: Prisma.EmailLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmailLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmailLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EmailLogs.
   */
  distinct?: Prisma.EmailLogScalarFieldEnum | Prisma.EmailLogScalarFieldEnum[]
}

/**
 * EmailLog findMany
 */
export type EmailLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailLog
   */
  select?: Prisma.EmailLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailLog
   */
  omit?: Prisma.EmailLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailLogInclude<ExtArgs> | null
  /**
   * Filter, which EmailLogs to fetch.
   */
  where?: Prisma.EmailLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmailLogs to fetch.
   */
  orderBy?: Prisma.EmailLogOrderByWithRelationInput | Prisma.EmailLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EmailLogs.
   */
  cursor?: Prisma.EmailLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmailLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmailLogs.
   */
  skip?: number
  distinct?: Prisma.EmailLogScalarFieldEnum | Prisma.EmailLogScalarFieldEnum[]
}

/**
 * EmailLog create
 */
export type EmailLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailLog
   */
  select?: Prisma.EmailLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailLog
   */
  omit?: Prisma.EmailLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailLogInclude<ExtArgs> | null
  /**
   * The data needed to create a EmailLog.
   */
  data: Prisma.XOR<Prisma.EmailLogCreateInput, Prisma.EmailLogUncheckedCreateInput>
}

/**
 * EmailLog createMany
 */
export type EmailLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EmailLogs.
   */
  data: Prisma.EmailLogCreateManyInput | Prisma.EmailLogCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EmailLog createManyAndReturn
 */
export type EmailLogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailLog
   */
  select?: Prisma.EmailLogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EmailLog
   */
  omit?: Prisma.EmailLogOmit<ExtArgs> | null
  /**
   * The data used to create many EmailLogs.
   */
  data: Prisma.EmailLogCreateManyInput | Prisma.EmailLogCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailLogIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * EmailLog update
 */
export type EmailLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailLog
   */
  select?: Prisma.EmailLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailLog
   */
  omit?: Prisma.EmailLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailLogInclude<ExtArgs> | null
  /**
   * The data needed to update a EmailLog.
   */
  data: Prisma.XOR<Prisma.EmailLogUpdateInput, Prisma.EmailLogUncheckedUpdateInput>
  /**
   * Choose, which EmailLog to update.
   */
  where: Prisma.EmailLogWhereUniqueInput
}

/**
 * EmailLog updateMany
 */
export type EmailLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EmailLogs.
   */
  data: Prisma.XOR<Prisma.EmailLogUpdateManyMutationInput, Prisma.EmailLogUncheckedUpdateManyInput>
  /**
   * Filter which EmailLogs to update
   */
  where?: Prisma.EmailLogWhereInput
  /**
   * Limit how many EmailLogs to update.
   */
  limit?: number
}

/**
 * EmailLog updateManyAndReturn
 */
export type EmailLogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailLog
   */
  select?: Prisma.EmailLogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EmailLog
   */
  omit?: Prisma.EmailLogOmit<ExtArgs> | null
  /**
   * The data used to update EmailLogs.
   */
  data: Prisma.XOR<Prisma.EmailLogUpdateManyMutationInput, Prisma.EmailLogUncheckedUpdateManyInput>
  /**
   * Filter which EmailLogs to update
   */
  where?: Prisma.EmailLogWhereInput
  /**
   * Limit how many EmailLogs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailLogIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * EmailLog upsert
 */
export type EmailLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailLog
   */
  select?: Prisma.EmailLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailLog
   */
  omit?: Prisma.EmailLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailLogInclude<ExtArgs> | null
  /**
   * The filter to search for the EmailLog to update in case it exists.
   */
  where: Prisma.EmailLogWhereUniqueInput
  /**
   * In case the EmailLog found by the `where` argument doesn't exist, create a new EmailLog with this data.
   */
  create: Prisma.XOR<Prisma.EmailLogCreateInput, Prisma.EmailLogUncheckedCreateInput>
  /**
   * In case the EmailLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EmailLogUpdateInput, Prisma.EmailLogUncheckedUpdateInput>
}

/**
 * EmailLog delete
 */
export type EmailLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailLog
   */
  select?: Prisma.EmailLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailLog
   */
  omit?: Prisma.EmailLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailLogInclude<ExtArgs> | null
  /**
   * Filter which EmailLog to delete.
   */
  where: Prisma.EmailLogWhereUniqueInput
}

/**
 * EmailLog deleteMany
 */
export type EmailLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EmailLogs to delete
   */
  where?: Prisma.EmailLogWhereInput
  /**
   * Limit how many EmailLogs to delete.
   */
  limit?: number
}

/**
 * EmailLog without action
 */
export type EmailLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailLog
   */
  select?: Prisma.EmailLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailLog
   */
  omit?: Prisma.EmailLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailLogInclude<ExtArgs> | null
}
