
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `NewsletterTag` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model NewsletterTag
 * 
 */
export type NewsletterTagModel = runtime.Types.Result.DefaultSelection<Prisma.$NewsletterTagPayload>

export type AggregateNewsletterTag = {
  _count: NewsletterTagCountAggregateOutputType | null
  _min: NewsletterTagMinAggregateOutputType | null
  _max: NewsletterTagMaxAggregateOutputType | null
}

export type NewsletterTagMinAggregateOutputType = {
  newsletterId: string | null
  tagId: string | null
}

export type NewsletterTagMaxAggregateOutputType = {
  newsletterId: string | null
  tagId: string | null
}

export type NewsletterTagCountAggregateOutputType = {
  newsletterId: number
  tagId: number
  _all: number
}


export type NewsletterTagMinAggregateInputType = {
  newsletterId?: true
  tagId?: true
}

export type NewsletterTagMaxAggregateInputType = {
  newsletterId?: true
  tagId?: true
}

export type NewsletterTagCountAggregateInputType = {
  newsletterId?: true
  tagId?: true
  _all?: true
}

export type NewsletterTagAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NewsletterTag to aggregate.
   */
  where?: Prisma.NewsletterTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewsletterTags to fetch.
   */
  orderBy?: Prisma.NewsletterTagOrderByWithRelationInput | Prisma.NewsletterTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NewsletterTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewsletterTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewsletterTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned NewsletterTags
  **/
  _count?: true | NewsletterTagCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NewsletterTagMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NewsletterTagMaxAggregateInputType
}

export type GetNewsletterTagAggregateType<T extends NewsletterTagAggregateArgs> = {
      [P in keyof T & keyof AggregateNewsletterTag]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNewsletterTag[P]>
    : Prisma.GetScalarType<T[P], AggregateNewsletterTag[P]>
}




export type NewsletterTagGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NewsletterTagWhereInput
  orderBy?: Prisma.NewsletterTagOrderByWithAggregationInput | Prisma.NewsletterTagOrderByWithAggregationInput[]
  by: Prisma.NewsletterTagScalarFieldEnum[] | Prisma.NewsletterTagScalarFieldEnum
  having?: Prisma.NewsletterTagScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NewsletterTagCountAggregateInputType | true
  _min?: NewsletterTagMinAggregateInputType
  _max?: NewsletterTagMaxAggregateInputType
}

export type NewsletterTagGroupByOutputType = {
  newsletterId: string
  tagId: string
  _count: NewsletterTagCountAggregateOutputType | null
  _min: NewsletterTagMinAggregateOutputType | null
  _max: NewsletterTagMaxAggregateOutputType | null
}

type GetNewsletterTagGroupByPayload<T extends NewsletterTagGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NewsletterTagGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NewsletterTagGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NewsletterTagGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NewsletterTagGroupByOutputType[P]>
      }
    >
  >



export type NewsletterTagWhereInput = {
  AND?: Prisma.NewsletterTagWhereInput | Prisma.NewsletterTagWhereInput[]
  OR?: Prisma.NewsletterTagWhereInput[]
  NOT?: Prisma.NewsletterTagWhereInput | Prisma.NewsletterTagWhereInput[]
  newsletterId?: Prisma.StringFilter<"NewsletterTag"> | string
  tagId?: Prisma.StringFilter<"NewsletterTag"> | string
  newsletter?: Prisma.XOR<Prisma.NewsletterScalarRelationFilter, Prisma.NewsletterWhereInput>
  tag?: Prisma.XOR<Prisma.TagScalarRelationFilter, Prisma.TagWhereInput>
}

export type NewsletterTagOrderByWithRelationInput = {
  newsletterId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  newsletter?: Prisma.NewsletterOrderByWithRelationInput
  tag?: Prisma.TagOrderByWithRelationInput
}

export type NewsletterTagWhereUniqueInput = Prisma.AtLeast<{
  newsletterId_tagId?: Prisma.NewsletterTagNewsletterIdTagIdCompoundUniqueInput
  AND?: Prisma.NewsletterTagWhereInput | Prisma.NewsletterTagWhereInput[]
  OR?: Prisma.NewsletterTagWhereInput[]
  NOT?: Prisma.NewsletterTagWhereInput | Prisma.NewsletterTagWhereInput[]
  newsletterId?: Prisma.StringFilter<"NewsletterTag"> | string
  tagId?: Prisma.StringFilter<"NewsletterTag"> | string
  newsletter?: Prisma.XOR<Prisma.NewsletterScalarRelationFilter, Prisma.NewsletterWhereInput>
  tag?: Prisma.XOR<Prisma.TagScalarRelationFilter, Prisma.TagWhereInput>
}, "newsletterId_tagId">

export type NewsletterTagOrderByWithAggregationInput = {
  newsletterId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  _count?: Prisma.NewsletterTagCountOrderByAggregateInput
  _max?: Prisma.NewsletterTagMaxOrderByAggregateInput
  _min?: Prisma.NewsletterTagMinOrderByAggregateInput
}

export type NewsletterTagScalarWhereWithAggregatesInput = {
  AND?: Prisma.NewsletterTagScalarWhereWithAggregatesInput | Prisma.NewsletterTagScalarWhereWithAggregatesInput[]
  OR?: Prisma.NewsletterTagScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NewsletterTagScalarWhereWithAggregatesInput | Prisma.NewsletterTagScalarWhereWithAggregatesInput[]
  newsletterId?: Prisma.StringWithAggregatesFilter<"NewsletterTag"> | string
  tagId?: Prisma.StringWithAggregatesFilter<"NewsletterTag"> | string
}

export type NewsletterTagCreateInput = {
  newsletter: Prisma.NewsletterCreateNestedOneWithoutNewsletterTagsInput
  tag: Prisma.TagCreateNestedOneWithoutNewsletterTagsInput
}

export type NewsletterTagUncheckedCreateInput = {
  newsletterId: string
  tagId: string
}

export type NewsletterTagUpdateInput = {
  newsletter?: Prisma.NewsletterUpdateOneRequiredWithoutNewsletterTagsNestedInput
  tag?: Prisma.TagUpdateOneRequiredWithoutNewsletterTagsNestedInput
}

export type NewsletterTagUncheckedUpdateInput = {
  newsletterId?: Prisma.StringFieldUpdateOperationsInput | string
  tagId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type NewsletterTagCreateManyInput = {
  newsletterId: string
  tagId: string
}

export type NewsletterTagUpdateManyMutationInput = {

}

export type NewsletterTagUncheckedUpdateManyInput = {
  newsletterId?: Prisma.StringFieldUpdateOperationsInput | string
  tagId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type NewsletterTagListRelationFilter = {
  every?: Prisma.NewsletterTagWhereInput
  some?: Prisma.NewsletterTagWhereInput
  none?: Prisma.NewsletterTagWhereInput
}

export type NewsletterTagOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NewsletterTagNewsletterIdTagIdCompoundUniqueInput = {
  newsletterId: string
  tagId: string
}

export type NewsletterTagCountOrderByAggregateInput = {
  newsletterId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
}

export type NewsletterTagMaxOrderByAggregateInput = {
  newsletterId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
}

export type NewsletterTagMinOrderByAggregateInput = {
  newsletterId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
}

export type NewsletterTagCreateNestedManyWithoutNewsletterInput = {
  create?: Prisma.XOR<Prisma.NewsletterTagCreateWithoutNewsletterInput, Prisma.NewsletterTagUncheckedCreateWithoutNewsletterInput> | Prisma.NewsletterTagCreateWithoutNewsletterInput[] | Prisma.NewsletterTagUncheckedCreateWithoutNewsletterInput[]
  connectOrCreate?: Prisma.NewsletterTagCreateOrConnectWithoutNewsletterInput | Prisma.NewsletterTagCreateOrConnectWithoutNewsletterInput[]
  createMany?: Prisma.NewsletterTagCreateManyNewsletterInputEnvelope
  connect?: Prisma.NewsletterTagWhereUniqueInput | Prisma.NewsletterTagWhereUniqueInput[]
}

export type NewsletterTagUncheckedCreateNestedManyWithoutNewsletterInput = {
  create?: Prisma.XOR<Prisma.NewsletterTagCreateWithoutNewsletterInput, Prisma.NewsletterTagUncheckedCreateWithoutNewsletterInput> | Prisma.NewsletterTagCreateWithoutNewsletterInput[] | Prisma.NewsletterTagUncheckedCreateWithoutNewsletterInput[]
  connectOrCreate?: Prisma.NewsletterTagCreateOrConnectWithoutNewsletterInput | Prisma.NewsletterTagCreateOrConnectWithoutNewsletterInput[]
  createMany?: Prisma.NewsletterTagCreateManyNewsletterInputEnvelope
  connect?: Prisma.NewsletterTagWhereUniqueInput | Prisma.NewsletterTagWhereUniqueInput[]
}

export type NewsletterTagUpdateManyWithoutNewsletterNestedInput = {
  create?: Prisma.XOR<Prisma.NewsletterTagCreateWithoutNewsletterInput, Prisma.NewsletterTagUncheckedCreateWithoutNewsletterInput> | Prisma.NewsletterTagCreateWithoutNewsletterInput[] | Prisma.NewsletterTagUncheckedCreateWithoutNewsletterInput[]
  connectOrCreate?: Prisma.NewsletterTagCreateOrConnectWithoutNewsletterInput | Prisma.NewsletterTagCreateOrConnectWithoutNewsletterInput[]
  upsert?: Prisma.NewsletterTagUpsertWithWhereUniqueWithoutNewsletterInput | Prisma.NewsletterTagUpsertWithWhereUniqueWithoutNewsletterInput[]
  createMany?: Prisma.NewsletterTagCreateManyNewsletterInputEnvelope
  set?: Prisma.NewsletterTagWhereUniqueInput | Prisma.NewsletterTagWhereUniqueInput[]
  disconnect?: Prisma.NewsletterTagWhereUniqueInput | Prisma.NewsletterTagWhereUniqueInput[]
  delete?: Prisma.NewsletterTagWhereUniqueInput | Prisma.NewsletterTagWhereUniqueInput[]
  connect?: Prisma.NewsletterTagWhereUniqueInput | Prisma.NewsletterTagWhereUniqueInput[]
  update?: Prisma.NewsletterTagUpdateWithWhereUniqueWithoutNewsletterInput | Prisma.NewsletterTagUpdateWithWhereUniqueWithoutNewsletterInput[]
  updateMany?: Prisma.NewsletterTagUpdateManyWithWhereWithoutNewsletterInput | Prisma.NewsletterTagUpdateManyWithWhereWithoutNewsletterInput[]
  deleteMany?: Prisma.NewsletterTagScalarWhereInput | Prisma.NewsletterTagScalarWhereInput[]
}

export type NewsletterTagUncheckedUpdateManyWithoutNewsletterNestedInput = {
  create?: Prisma.XOR<Prisma.NewsletterTagCreateWithoutNewsletterInput, Prisma.NewsletterTagUncheckedCreateWithoutNewsletterInput> | Prisma.NewsletterTagCreateWithoutNewsletterInput[] | Prisma.NewsletterTagUncheckedCreateWithoutNewsletterInput[]
  connectOrCreate?: Prisma.NewsletterTagCreateOrConnectWithoutNewsletterInput | Prisma.NewsletterTagCreateOrConnectWithoutNewsletterInput[]
  upsert?: Prisma.NewsletterTagUpsertWithWhereUniqueWithoutNewsletterInput | Prisma.NewsletterTagUpsertWithWhereUniqueWithoutNewsletterInput[]
  createMany?: Prisma.NewsletterTagCreateManyNewsletterInputEnvelope
  set?: Prisma.NewsletterTagWhereUniqueInput | Prisma.NewsletterTagWhereUniqueInput[]
  disconnect?: Prisma.NewsletterTagWhereUniqueInput | Prisma.NewsletterTagWhereUniqueInput[]
  delete?: Prisma.NewsletterTagWhereUniqueInput | Prisma.NewsletterTagWhereUniqueInput[]
  connect?: Prisma.NewsletterTagWhereUniqueInput | Prisma.NewsletterTagWhereUniqueInput[]
  update?: Prisma.NewsletterTagUpdateWithWhereUniqueWithoutNewsletterInput | Prisma.NewsletterTagUpdateWithWhereUniqueWithoutNewsletterInput[]
  updateMany?: Prisma.NewsletterTagUpdateManyWithWhereWithoutNewsletterInput | Prisma.NewsletterTagUpdateManyWithWhereWithoutNewsletterInput[]
  deleteMany?: Prisma.NewsletterTagScalarWhereInput | Prisma.NewsletterTagScalarWhereInput[]
}

export type NewsletterTagCreateNestedManyWithoutTagInput = {
  create?: Prisma.XOR<Prisma.NewsletterTagCreateWithoutTagInput, Prisma.NewsletterTagUncheckedCreateWithoutTagInput> | Prisma.NewsletterTagCreateWithoutTagInput[] | Prisma.NewsletterTagUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.NewsletterTagCreateOrConnectWithoutTagInput | Prisma.NewsletterTagCreateOrConnectWithoutTagInput[]
  createMany?: Prisma.NewsletterTagCreateManyTagInputEnvelope
  connect?: Prisma.NewsletterTagWhereUniqueInput | Prisma.NewsletterTagWhereUniqueInput[]
}

export type NewsletterTagUncheckedCreateNestedManyWithoutTagInput = {
  create?: Prisma.XOR<Prisma.NewsletterTagCreateWithoutTagInput, Prisma.NewsletterTagUncheckedCreateWithoutTagInput> | Prisma.NewsletterTagCreateWithoutTagInput[] | Prisma.NewsletterTagUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.NewsletterTagCreateOrConnectWithoutTagInput | Prisma.NewsletterTagCreateOrConnectWithoutTagInput[]
  createMany?: Prisma.NewsletterTagCreateManyTagInputEnvelope
  connect?: Prisma.NewsletterTagWhereUniqueInput | Prisma.NewsletterTagWhereUniqueInput[]
}

export type NewsletterTagUpdateManyWithoutTagNestedInput = {
  create?: Prisma.XOR<Prisma.NewsletterTagCreateWithoutTagInput, Prisma.NewsletterTagUncheckedCreateWithoutTagInput> | Prisma.NewsletterTagCreateWithoutTagInput[] | Prisma.NewsletterTagUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.NewsletterTagCreateOrConnectWithoutTagInput | Prisma.NewsletterTagCreateOrConnectWithoutTagInput[]
  upsert?: Prisma.NewsletterTagUpsertWithWhereUniqueWithoutTagInput | Prisma.NewsletterTagUpsertWithWhereUniqueWithoutTagInput[]
  createMany?: Prisma.NewsletterTagCreateManyTagInputEnvelope
  set?: Prisma.NewsletterTagWhereUniqueInput | Prisma.NewsletterTagWhereUniqueInput[]
  disconnect?: Prisma.NewsletterTagWhereUniqueInput | Prisma.NewsletterTagWhereUniqueInput[]
  delete?: Prisma.NewsletterTagWhereUniqueInput | Prisma.NewsletterTagWhereUniqueInput[]
  connect?: Prisma.NewsletterTagWhereUniqueInput | Prisma.NewsletterTagWhereUniqueInput[]
  update?: Prisma.NewsletterTagUpdateWithWhereUniqueWithoutTagInput | Prisma.NewsletterTagUpdateWithWhereUniqueWithoutTagInput[]
  updateMany?: Prisma.NewsletterTagUpdateManyWithWhereWithoutTagInput | Prisma.NewsletterTagUpdateManyWithWhereWithoutTagInput[]
  deleteMany?: Prisma.NewsletterTagScalarWhereInput | Prisma.NewsletterTagScalarWhereInput[]
}

export type NewsletterTagUncheckedUpdateManyWithoutTagNestedInput = {
  create?: Prisma.XOR<Prisma.NewsletterTagCreateWithoutTagInput, Prisma.NewsletterTagUncheckedCreateWithoutTagInput> | Prisma.NewsletterTagCreateWithoutTagInput[] | Prisma.NewsletterTagUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.NewsletterTagCreateOrConnectWithoutTagInput | Prisma.NewsletterTagCreateOrConnectWithoutTagInput[]
  upsert?: Prisma.NewsletterTagUpsertWithWhereUniqueWithoutTagInput | Prisma.NewsletterTagUpsertWithWhereUniqueWithoutTagInput[]
  createMany?: Prisma.NewsletterTagCreateManyTagInputEnvelope
  set?: Prisma.NewsletterTagWhereUniqueInput | Prisma.NewsletterTagWhereUniqueInput[]
  disconnect?: Prisma.NewsletterTagWhereUniqueInput | Prisma.NewsletterTagWhereUniqueInput[]
  delete?: Prisma.NewsletterTagWhereUniqueInput | Prisma.NewsletterTagWhereUniqueInput[]
  connect?: Prisma.NewsletterTagWhereUniqueInput | Prisma.NewsletterTagWhereUniqueInput[]
  update?: Prisma.NewsletterTagUpdateWithWhereUniqueWithoutTagInput | Prisma.NewsletterTagUpdateWithWhereUniqueWithoutTagInput[]
  updateMany?: Prisma.NewsletterTagUpdateManyWithWhereWithoutTagInput | Prisma.NewsletterTagUpdateManyWithWhereWithoutTagInput[]
  deleteMany?: Prisma.NewsletterTagScalarWhereInput | Prisma.NewsletterTagScalarWhereInput[]
}

export type NewsletterTagCreateWithoutNewsletterInput = {
  tag: Prisma.TagCreateNestedOneWithoutNewsletterTagsInput
}

export type NewsletterTagUncheckedCreateWithoutNewsletterInput = {
  tagId: string
}

export type NewsletterTagCreateOrConnectWithoutNewsletterInput = {
  where: Prisma.NewsletterTagWhereUniqueInput
  create: Prisma.XOR<Prisma.NewsletterTagCreateWithoutNewsletterInput, Prisma.NewsletterTagUncheckedCreateWithoutNewsletterInput>
}

export type NewsletterTagCreateManyNewsletterInputEnvelope = {
  data: Prisma.NewsletterTagCreateManyNewsletterInput | Prisma.NewsletterTagCreateManyNewsletterInput[]
  skipDuplicates?: boolean
}

export type NewsletterTagUpsertWithWhereUniqueWithoutNewsletterInput = {
  where: Prisma.NewsletterTagWhereUniqueInput
  update: Prisma.XOR<Prisma.NewsletterTagUpdateWithoutNewsletterInput, Prisma.NewsletterTagUncheckedUpdateWithoutNewsletterInput>
  create: Prisma.XOR<Prisma.NewsletterTagCreateWithoutNewsletterInput, Prisma.NewsletterTagUncheckedCreateWithoutNewsletterInput>
}

export type NewsletterTagUpdateWithWhereUniqueWithoutNewsletterInput = {
  where: Prisma.NewsletterTagWhereUniqueInput
  data: Prisma.XOR<Prisma.NewsletterTagUpdateWithoutNewsletterInput, Prisma.NewsletterTagUncheckedUpdateWithoutNewsletterInput>
}

export type NewsletterTagUpdateManyWithWhereWithoutNewsletterInput = {
  where: Prisma.NewsletterTagScalarWhereInput
  data: Prisma.XOR<Prisma.NewsletterTagUpdateManyMutationInput, Prisma.NewsletterTagUncheckedUpdateManyWithoutNewsletterInput>
}

export type NewsletterTagScalarWhereInput = {
  AND?: Prisma.NewsletterTagScalarWhereInput | Prisma.NewsletterTagScalarWhereInput[]
  OR?: Prisma.NewsletterTagScalarWhereInput[]
  NOT?: Prisma.NewsletterTagScalarWhereInput | Prisma.NewsletterTagScalarWhereInput[]
  newsletterId?: Prisma.StringFilter<"NewsletterTag"> | string
  tagId?: Prisma.StringFilter<"NewsletterTag"> | string
}

export type NewsletterTagCreateWithoutTagInput = {
  newsletter: Prisma.NewsletterCreateNestedOneWithoutNewsletterTagsInput
}

export type NewsletterTagUncheckedCreateWithoutTagInput = {
  newsletterId: string
}

export type NewsletterTagCreateOrConnectWithoutTagInput = {
  where: Prisma.NewsletterTagWhereUniqueInput
  create: Prisma.XOR<Prisma.NewsletterTagCreateWithoutTagInput, Prisma.NewsletterTagUncheckedCreateWithoutTagInput>
}

export type NewsletterTagCreateManyTagInputEnvelope = {
  data: Prisma.NewsletterTagCreateManyTagInput | Prisma.NewsletterTagCreateManyTagInput[]
  skipDuplicates?: boolean
}

export type NewsletterTagUpsertWithWhereUniqueWithoutTagInput = {
  where: Prisma.NewsletterTagWhereUniqueInput
  update: Prisma.XOR<Prisma.NewsletterTagUpdateWithoutTagInput, Prisma.NewsletterTagUncheckedUpdateWithoutTagInput>
  create: Prisma.XOR<Prisma.NewsletterTagCreateWithoutTagInput, Prisma.NewsletterTagUncheckedCreateWithoutTagInput>
}

export type NewsletterTagUpdateWithWhereUniqueWithoutTagInput = {
  where: Prisma.NewsletterTagWhereUniqueInput
  data: Prisma.XOR<Prisma.NewsletterTagUpdateWithoutTagInput, Prisma.NewsletterTagUncheckedUpdateWithoutTagInput>
}

export type NewsletterTagUpdateManyWithWhereWithoutTagInput = {
  where: Prisma.NewsletterTagScalarWhereInput
  data: Prisma.XOR<Prisma.NewsletterTagUpdateManyMutationInput, Prisma.NewsletterTagUncheckedUpdateManyWithoutTagInput>
}

export type NewsletterTagCreateManyNewsletterInput = {
  tagId: string
}

export type NewsletterTagUpdateWithoutNewsletterInput = {
  tag?: Prisma.TagUpdateOneRequiredWithoutNewsletterTagsNestedInput
}

export type NewsletterTagUncheckedUpdateWithoutNewsletterInput = {
  tagId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type NewsletterTagUncheckedUpdateManyWithoutNewsletterInput = {
  tagId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type NewsletterTagCreateManyTagInput = {
  newsletterId: string
}

export type NewsletterTagUpdateWithoutTagInput = {
  newsletter?: Prisma.NewsletterUpdateOneRequiredWithoutNewsletterTagsNestedInput
}

export type NewsletterTagUncheckedUpdateWithoutTagInput = {
  newsletterId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type NewsletterTagUncheckedUpdateManyWithoutTagInput = {
  newsletterId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type NewsletterTagSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  newsletterId?: boolean
  tagId?: boolean
  newsletter?: boolean | Prisma.NewsletterDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["newsletterTag"]>

export type NewsletterTagSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  newsletterId?: boolean
  tagId?: boolean
  newsletter?: boolean | Prisma.NewsletterDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["newsletterTag"]>

export type NewsletterTagSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  newsletterId?: boolean
  tagId?: boolean
  newsletter?: boolean | Prisma.NewsletterDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["newsletterTag"]>

export type NewsletterTagSelectScalar = {
  newsletterId?: boolean
  tagId?: boolean
}

export type NewsletterTagOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"newsletterId" | "tagId", ExtArgs["result"]["newsletterTag"]>
export type NewsletterTagInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  newsletter?: boolean | Prisma.NewsletterDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}
export type NewsletterTagIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  newsletter?: boolean | Prisma.NewsletterDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}
export type NewsletterTagIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  newsletter?: boolean | Prisma.NewsletterDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}

export type $NewsletterTagPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "NewsletterTag"
  objects: {
    newsletter: Prisma.$NewsletterPayload<ExtArgs>
    tag: Prisma.$TagPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    newsletterId: string
    tagId: string
  }, ExtArgs["result"]["newsletterTag"]>
  composites: {}
}

export type NewsletterTagGetPayload<S extends boolean | null | undefined | NewsletterTagDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NewsletterTagPayload, S>

export type NewsletterTagCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NewsletterTagFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NewsletterTagCountAggregateInputType | true
  }

export interface NewsletterTagDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['NewsletterTag'], meta: { name: 'NewsletterTag' } }
  /**
   * Find zero or one NewsletterTag that matches the filter.
   * @param {NewsletterTagFindUniqueArgs} args - Arguments to find a NewsletterTag
   * @example
   * // Get one NewsletterTag
   * const newsletterTag = await prisma.newsletterTag.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NewsletterTagFindUniqueArgs>(args: Prisma.SelectSubset<T, NewsletterTagFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NewsletterTagClient<runtime.Types.Result.GetResult<Prisma.$NewsletterTagPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one NewsletterTag that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NewsletterTagFindUniqueOrThrowArgs} args - Arguments to find a NewsletterTag
   * @example
   * // Get one NewsletterTag
   * const newsletterTag = await prisma.newsletterTag.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NewsletterTagFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NewsletterTagFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NewsletterTagClient<runtime.Types.Result.GetResult<Prisma.$NewsletterTagPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NewsletterTag that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsletterTagFindFirstArgs} args - Arguments to find a NewsletterTag
   * @example
   * // Get one NewsletterTag
   * const newsletterTag = await prisma.newsletterTag.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NewsletterTagFindFirstArgs>(args?: Prisma.SelectSubset<T, NewsletterTagFindFirstArgs<ExtArgs>>): Prisma.Prisma__NewsletterTagClient<runtime.Types.Result.GetResult<Prisma.$NewsletterTagPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NewsletterTag that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsletterTagFindFirstOrThrowArgs} args - Arguments to find a NewsletterTag
   * @example
   * // Get one NewsletterTag
   * const newsletterTag = await prisma.newsletterTag.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NewsletterTagFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NewsletterTagFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NewsletterTagClient<runtime.Types.Result.GetResult<Prisma.$NewsletterTagPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more NewsletterTags that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsletterTagFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all NewsletterTags
   * const newsletterTags = await prisma.newsletterTag.findMany()
   * 
   * // Get first 10 NewsletterTags
   * const newsletterTags = await prisma.newsletterTag.findMany({ take: 10 })
   * 
   * // Only select the `newsletterId`
   * const newsletterTagWithNewsletterIdOnly = await prisma.newsletterTag.findMany({ select: { newsletterId: true } })
   * 
   */
  findMany<T extends NewsletterTagFindManyArgs>(args?: Prisma.SelectSubset<T, NewsletterTagFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NewsletterTagPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a NewsletterTag.
   * @param {NewsletterTagCreateArgs} args - Arguments to create a NewsletterTag.
   * @example
   * // Create one NewsletterTag
   * const NewsletterTag = await prisma.newsletterTag.create({
   *   data: {
   *     // ... data to create a NewsletterTag
   *   }
   * })
   * 
   */
  create<T extends NewsletterTagCreateArgs>(args: Prisma.SelectSubset<T, NewsletterTagCreateArgs<ExtArgs>>): Prisma.Prisma__NewsletterTagClient<runtime.Types.Result.GetResult<Prisma.$NewsletterTagPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many NewsletterTags.
   * @param {NewsletterTagCreateManyArgs} args - Arguments to create many NewsletterTags.
   * @example
   * // Create many NewsletterTags
   * const newsletterTag = await prisma.newsletterTag.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NewsletterTagCreateManyArgs>(args?: Prisma.SelectSubset<T, NewsletterTagCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many NewsletterTags and returns the data saved in the database.
   * @param {NewsletterTagCreateManyAndReturnArgs} args - Arguments to create many NewsletterTags.
   * @example
   * // Create many NewsletterTags
   * const newsletterTag = await prisma.newsletterTag.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many NewsletterTags and only return the `newsletterId`
   * const newsletterTagWithNewsletterIdOnly = await prisma.newsletterTag.createManyAndReturn({
   *   select: { newsletterId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends NewsletterTagCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, NewsletterTagCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NewsletterTagPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a NewsletterTag.
   * @param {NewsletterTagDeleteArgs} args - Arguments to delete one NewsletterTag.
   * @example
   * // Delete one NewsletterTag
   * const NewsletterTag = await prisma.newsletterTag.delete({
   *   where: {
   *     // ... filter to delete one NewsletterTag
   *   }
   * })
   * 
   */
  delete<T extends NewsletterTagDeleteArgs>(args: Prisma.SelectSubset<T, NewsletterTagDeleteArgs<ExtArgs>>): Prisma.Prisma__NewsletterTagClient<runtime.Types.Result.GetResult<Prisma.$NewsletterTagPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one NewsletterTag.
   * @param {NewsletterTagUpdateArgs} args - Arguments to update one NewsletterTag.
   * @example
   * // Update one NewsletterTag
   * const newsletterTag = await prisma.newsletterTag.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NewsletterTagUpdateArgs>(args: Prisma.SelectSubset<T, NewsletterTagUpdateArgs<ExtArgs>>): Prisma.Prisma__NewsletterTagClient<runtime.Types.Result.GetResult<Prisma.$NewsletterTagPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more NewsletterTags.
   * @param {NewsletterTagDeleteManyArgs} args - Arguments to filter NewsletterTags to delete.
   * @example
   * // Delete a few NewsletterTags
   * const { count } = await prisma.newsletterTag.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NewsletterTagDeleteManyArgs>(args?: Prisma.SelectSubset<T, NewsletterTagDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NewsletterTags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsletterTagUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many NewsletterTags
   * const newsletterTag = await prisma.newsletterTag.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NewsletterTagUpdateManyArgs>(args: Prisma.SelectSubset<T, NewsletterTagUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NewsletterTags and returns the data updated in the database.
   * @param {NewsletterTagUpdateManyAndReturnArgs} args - Arguments to update many NewsletterTags.
   * @example
   * // Update many NewsletterTags
   * const newsletterTag = await prisma.newsletterTag.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more NewsletterTags and only return the `newsletterId`
   * const newsletterTagWithNewsletterIdOnly = await prisma.newsletterTag.updateManyAndReturn({
   *   select: { newsletterId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends NewsletterTagUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, NewsletterTagUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NewsletterTagPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one NewsletterTag.
   * @param {NewsletterTagUpsertArgs} args - Arguments to update or create a NewsletterTag.
   * @example
   * // Update or create a NewsletterTag
   * const newsletterTag = await prisma.newsletterTag.upsert({
   *   create: {
   *     // ... data to create a NewsletterTag
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the NewsletterTag we want to update
   *   }
   * })
   */
  upsert<T extends NewsletterTagUpsertArgs>(args: Prisma.SelectSubset<T, NewsletterTagUpsertArgs<ExtArgs>>): Prisma.Prisma__NewsletterTagClient<runtime.Types.Result.GetResult<Prisma.$NewsletterTagPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of NewsletterTags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsletterTagCountArgs} args - Arguments to filter NewsletterTags to count.
   * @example
   * // Count the number of NewsletterTags
   * const count = await prisma.newsletterTag.count({
   *   where: {
   *     // ... the filter for the NewsletterTags we want to count
   *   }
   * })
  **/
  count<T extends NewsletterTagCountArgs>(
    args?: Prisma.Subset<T, NewsletterTagCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NewsletterTagCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a NewsletterTag.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsletterTagAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NewsletterTagAggregateArgs>(args: Prisma.Subset<T, NewsletterTagAggregateArgs>): Prisma.PrismaPromise<GetNewsletterTagAggregateType<T>>

  /**
   * Group by NewsletterTag.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsletterTagGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NewsletterTagGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NewsletterTagGroupByArgs['orderBy'] }
      : { orderBy?: NewsletterTagGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NewsletterTagGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNewsletterTagGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the NewsletterTag model
 */
readonly fields: NewsletterTagFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for NewsletterTag.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NewsletterTagClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  newsletter<T extends Prisma.NewsletterDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.NewsletterDefaultArgs<ExtArgs>>): Prisma.Prisma__NewsletterClient<runtime.Types.Result.GetResult<Prisma.$NewsletterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  tag<T extends Prisma.TagDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TagDefaultArgs<ExtArgs>>): Prisma.Prisma__TagClient<runtime.Types.Result.GetResult<Prisma.$TagPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the NewsletterTag model
 */
export interface NewsletterTagFieldRefs {
  readonly newsletterId: Prisma.FieldRef<"NewsletterTag", 'String'>
  readonly tagId: Prisma.FieldRef<"NewsletterTag", 'String'>
}
    

// Custom InputTypes
/**
 * NewsletterTag findUnique
 */
export type NewsletterTagFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterTag
   */
  select?: Prisma.NewsletterTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterTag
   */
  omit?: Prisma.NewsletterTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterTagInclude<ExtArgs> | null
  /**
   * Filter, which NewsletterTag to fetch.
   */
  where: Prisma.NewsletterTagWhereUniqueInput
}

/**
 * NewsletterTag findUniqueOrThrow
 */
export type NewsletterTagFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterTag
   */
  select?: Prisma.NewsletterTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterTag
   */
  omit?: Prisma.NewsletterTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterTagInclude<ExtArgs> | null
  /**
   * Filter, which NewsletterTag to fetch.
   */
  where: Prisma.NewsletterTagWhereUniqueInput
}

/**
 * NewsletterTag findFirst
 */
export type NewsletterTagFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterTag
   */
  select?: Prisma.NewsletterTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterTag
   */
  omit?: Prisma.NewsletterTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterTagInclude<ExtArgs> | null
  /**
   * Filter, which NewsletterTag to fetch.
   */
  where?: Prisma.NewsletterTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewsletterTags to fetch.
   */
  orderBy?: Prisma.NewsletterTagOrderByWithRelationInput | Prisma.NewsletterTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NewsletterTags.
   */
  cursor?: Prisma.NewsletterTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewsletterTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewsletterTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NewsletterTags.
   */
  distinct?: Prisma.NewsletterTagScalarFieldEnum | Prisma.NewsletterTagScalarFieldEnum[]
}

/**
 * NewsletterTag findFirstOrThrow
 */
export type NewsletterTagFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterTag
   */
  select?: Prisma.NewsletterTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterTag
   */
  omit?: Prisma.NewsletterTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterTagInclude<ExtArgs> | null
  /**
   * Filter, which NewsletterTag to fetch.
   */
  where?: Prisma.NewsletterTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewsletterTags to fetch.
   */
  orderBy?: Prisma.NewsletterTagOrderByWithRelationInput | Prisma.NewsletterTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NewsletterTags.
   */
  cursor?: Prisma.NewsletterTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewsletterTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewsletterTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NewsletterTags.
   */
  distinct?: Prisma.NewsletterTagScalarFieldEnum | Prisma.NewsletterTagScalarFieldEnum[]
}

/**
 * NewsletterTag findMany
 */
export type NewsletterTagFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterTag
   */
  select?: Prisma.NewsletterTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterTag
   */
  omit?: Prisma.NewsletterTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterTagInclude<ExtArgs> | null
  /**
   * Filter, which NewsletterTags to fetch.
   */
  where?: Prisma.NewsletterTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewsletterTags to fetch.
   */
  orderBy?: Prisma.NewsletterTagOrderByWithRelationInput | Prisma.NewsletterTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing NewsletterTags.
   */
  cursor?: Prisma.NewsletterTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewsletterTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewsletterTags.
   */
  skip?: number
  distinct?: Prisma.NewsletterTagScalarFieldEnum | Prisma.NewsletterTagScalarFieldEnum[]
}

/**
 * NewsletterTag create
 */
export type NewsletterTagCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterTag
   */
  select?: Prisma.NewsletterTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterTag
   */
  omit?: Prisma.NewsletterTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterTagInclude<ExtArgs> | null
  /**
   * The data needed to create a NewsletterTag.
   */
  data: Prisma.XOR<Prisma.NewsletterTagCreateInput, Prisma.NewsletterTagUncheckedCreateInput>
}

/**
 * NewsletterTag createMany
 */
export type NewsletterTagCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many NewsletterTags.
   */
  data: Prisma.NewsletterTagCreateManyInput | Prisma.NewsletterTagCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * NewsletterTag createManyAndReturn
 */
export type NewsletterTagCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterTag
   */
  select?: Prisma.NewsletterTagSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterTag
   */
  omit?: Prisma.NewsletterTagOmit<ExtArgs> | null
  /**
   * The data used to create many NewsletterTags.
   */
  data: Prisma.NewsletterTagCreateManyInput | Prisma.NewsletterTagCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterTagIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * NewsletterTag update
 */
export type NewsletterTagUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterTag
   */
  select?: Prisma.NewsletterTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterTag
   */
  omit?: Prisma.NewsletterTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterTagInclude<ExtArgs> | null
  /**
   * The data needed to update a NewsletterTag.
   */
  data: Prisma.XOR<Prisma.NewsletterTagUpdateInput, Prisma.NewsletterTagUncheckedUpdateInput>
  /**
   * Choose, which NewsletterTag to update.
   */
  where: Prisma.NewsletterTagWhereUniqueInput
}

/**
 * NewsletterTag updateMany
 */
export type NewsletterTagUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update NewsletterTags.
   */
  data: Prisma.XOR<Prisma.NewsletterTagUpdateManyMutationInput, Prisma.NewsletterTagUncheckedUpdateManyInput>
  /**
   * Filter which NewsletterTags to update
   */
  where?: Prisma.NewsletterTagWhereInput
  /**
   * Limit how many NewsletterTags to update.
   */
  limit?: number
}

/**
 * NewsletterTag updateManyAndReturn
 */
export type NewsletterTagUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterTag
   */
  select?: Prisma.NewsletterTagSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterTag
   */
  omit?: Prisma.NewsletterTagOmit<ExtArgs> | null
  /**
   * The data used to update NewsletterTags.
   */
  data: Prisma.XOR<Prisma.NewsletterTagUpdateManyMutationInput, Prisma.NewsletterTagUncheckedUpdateManyInput>
  /**
   * Filter which NewsletterTags to update
   */
  where?: Prisma.NewsletterTagWhereInput
  /**
   * Limit how many NewsletterTags to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterTagIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * NewsletterTag upsert
 */
export type NewsletterTagUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterTag
   */
  select?: Prisma.NewsletterTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterTag
   */
  omit?: Prisma.NewsletterTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterTagInclude<ExtArgs> | null
  /**
   * The filter to search for the NewsletterTag to update in case it exists.
   */
  where: Prisma.NewsletterTagWhereUniqueInput
  /**
   * In case the NewsletterTag found by the `where` argument doesn't exist, create a new NewsletterTag with this data.
   */
  create: Prisma.XOR<Prisma.NewsletterTagCreateInput, Prisma.NewsletterTagUncheckedCreateInput>
  /**
   * In case the NewsletterTag was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NewsletterTagUpdateInput, Prisma.NewsletterTagUncheckedUpdateInput>
}

/**
 * NewsletterTag delete
 */
export type NewsletterTagDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterTag
   */
  select?: Prisma.NewsletterTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterTag
   */
  omit?: Prisma.NewsletterTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterTagInclude<ExtArgs> | null
  /**
   * Filter which NewsletterTag to delete.
   */
  where: Prisma.NewsletterTagWhereUniqueInput
}

/**
 * NewsletterTag deleteMany
 */
export type NewsletterTagDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NewsletterTags to delete
   */
  where?: Prisma.NewsletterTagWhereInput
  /**
   * Limit how many NewsletterTags to delete.
   */
  limit?: number
}

/**
 * NewsletterTag without action
 */
export type NewsletterTagDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterTag
   */
  select?: Prisma.NewsletterTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterTag
   */
  omit?: Prisma.NewsletterTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterTagInclude<ExtArgs> | null
}
