
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Subscriber` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Subscriber
 * Newsletter subscriber. Email is required; phone is optional and used for WhatsApp when whatsappOptIn is true.
 * Phone is unique when set so one number cannot be associated with multiple accounts.
 */
export type SubscriberModel = runtime.Types.Result.DefaultSelection<Prisma.$SubscriberPayload>

export type AggregateSubscriber = {
  _count: SubscriberCountAggregateOutputType | null
  _min: SubscriberMinAggregateOutputType | null
  _max: SubscriberMaxAggregateOutputType | null
}

export type SubscriberMinAggregateOutputType = {
  id: string | null
  email: string | null
  name: string | null
  phone: string | null
  whatsappOptIn: boolean | null
  status: $Enums.SubscriberStatus | null
  createdAt: Date | null
  updatedAt: Date | null
  unsubscribedAt: Date | null
  confirmToken: string | null
  confirmSentAt: Date | null
}

export type SubscriberMaxAggregateOutputType = {
  id: string | null
  email: string | null
  name: string | null
  phone: string | null
  whatsappOptIn: boolean | null
  status: $Enums.SubscriberStatus | null
  createdAt: Date | null
  updatedAt: Date | null
  unsubscribedAt: Date | null
  confirmToken: string | null
  confirmSentAt: Date | null
}

export type SubscriberCountAggregateOutputType = {
  id: number
  email: number
  name: number
  phone: number
  whatsappOptIn: number
  status: number
  createdAt: number
  updatedAt: number
  unsubscribedAt: number
  confirmToken: number
  confirmSentAt: number
  meta: number
  _all: number
}


export type SubscriberMinAggregateInputType = {
  id?: true
  email?: true
  name?: true
  phone?: true
  whatsappOptIn?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  unsubscribedAt?: true
  confirmToken?: true
  confirmSentAt?: true
}

export type SubscriberMaxAggregateInputType = {
  id?: true
  email?: true
  name?: true
  phone?: true
  whatsappOptIn?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  unsubscribedAt?: true
  confirmToken?: true
  confirmSentAt?: true
}

export type SubscriberCountAggregateInputType = {
  id?: true
  email?: true
  name?: true
  phone?: true
  whatsappOptIn?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  unsubscribedAt?: true
  confirmToken?: true
  confirmSentAt?: true
  meta?: true
  _all?: true
}

export type SubscriberAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Subscriber to aggregate.
   */
  where?: Prisma.SubscriberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Subscribers to fetch.
   */
  orderBy?: Prisma.SubscriberOrderByWithRelationInput | Prisma.SubscriberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SubscriberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Subscribers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Subscribers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Subscribers
  **/
  _count?: true | SubscriberCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SubscriberMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SubscriberMaxAggregateInputType
}

export type GetSubscriberAggregateType<T extends SubscriberAggregateArgs> = {
      [P in keyof T & keyof AggregateSubscriber]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSubscriber[P]>
    : Prisma.GetScalarType<T[P], AggregateSubscriber[P]>
}




export type SubscriberGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SubscriberWhereInput
  orderBy?: Prisma.SubscriberOrderByWithAggregationInput | Prisma.SubscriberOrderByWithAggregationInput[]
  by: Prisma.SubscriberScalarFieldEnum[] | Prisma.SubscriberScalarFieldEnum
  having?: Prisma.SubscriberScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SubscriberCountAggregateInputType | true
  _min?: SubscriberMinAggregateInputType
  _max?: SubscriberMaxAggregateInputType
}

export type SubscriberGroupByOutputType = {
  id: string
  email: string
  name: string | null
  phone: string | null
  whatsappOptIn: boolean
  status: $Enums.SubscriberStatus
  createdAt: Date
  updatedAt: Date
  unsubscribedAt: Date | null
  confirmToken: string | null
  confirmSentAt: Date | null
  meta: runtime.JsonValue | null
  _count: SubscriberCountAggregateOutputType | null
  _min: SubscriberMinAggregateOutputType | null
  _max: SubscriberMaxAggregateOutputType | null
}

type GetSubscriberGroupByPayload<T extends SubscriberGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SubscriberGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SubscriberGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SubscriberGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SubscriberGroupByOutputType[P]>
      }
    >
  >



export type SubscriberWhereInput = {
  AND?: Prisma.SubscriberWhereInput | Prisma.SubscriberWhereInput[]
  OR?: Prisma.SubscriberWhereInput[]
  NOT?: Prisma.SubscriberWhereInput | Prisma.SubscriberWhereInput[]
  id?: Prisma.StringFilter<"Subscriber"> | string
  email?: Prisma.StringFilter<"Subscriber"> | string
  name?: Prisma.StringNullableFilter<"Subscriber"> | string | null
  phone?: Prisma.StringNullableFilter<"Subscriber"> | string | null
  whatsappOptIn?: Prisma.BoolFilter<"Subscriber"> | boolean
  status?: Prisma.EnumSubscriberStatusFilter<"Subscriber"> | $Enums.SubscriberStatus
  createdAt?: Prisma.DateTimeFilter<"Subscriber"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Subscriber"> | Date | string
  unsubscribedAt?: Prisma.DateTimeNullableFilter<"Subscriber"> | Date | string | null
  confirmToken?: Prisma.StringNullableFilter<"Subscriber"> | string | null
  confirmSentAt?: Prisma.DateTimeNullableFilter<"Subscriber"> | Date | string | null
  meta?: Prisma.JsonNullableFilter<"Subscriber">
  emailLogs?: Prisma.EmailLogListRelationFilter
}

export type SubscriberOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  whatsappOptIn?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  unsubscribedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  confirmToken?: Prisma.SortOrderInput | Prisma.SortOrder
  confirmSentAt?: Prisma.SortOrderInput | Prisma.SortOrder
  meta?: Prisma.SortOrderInput | Prisma.SortOrder
  emailLogs?: Prisma.EmailLogOrderByRelationAggregateInput
}

export type SubscriberWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  phone?: string
  confirmToken?: string
  AND?: Prisma.SubscriberWhereInput | Prisma.SubscriberWhereInput[]
  OR?: Prisma.SubscriberWhereInput[]
  NOT?: Prisma.SubscriberWhereInput | Prisma.SubscriberWhereInput[]
  name?: Prisma.StringNullableFilter<"Subscriber"> | string | null
  whatsappOptIn?: Prisma.BoolFilter<"Subscriber"> | boolean
  status?: Prisma.EnumSubscriberStatusFilter<"Subscriber"> | $Enums.SubscriberStatus
  createdAt?: Prisma.DateTimeFilter<"Subscriber"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Subscriber"> | Date | string
  unsubscribedAt?: Prisma.DateTimeNullableFilter<"Subscriber"> | Date | string | null
  confirmSentAt?: Prisma.DateTimeNullableFilter<"Subscriber"> | Date | string | null
  meta?: Prisma.JsonNullableFilter<"Subscriber">
  emailLogs?: Prisma.EmailLogListRelationFilter
}, "id" | "email" | "phone" | "confirmToken">

export type SubscriberOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  whatsappOptIn?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  unsubscribedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  confirmToken?: Prisma.SortOrderInput | Prisma.SortOrder
  confirmSentAt?: Prisma.SortOrderInput | Prisma.SortOrder
  meta?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.SubscriberCountOrderByAggregateInput
  _max?: Prisma.SubscriberMaxOrderByAggregateInput
  _min?: Prisma.SubscriberMinOrderByAggregateInput
}

export type SubscriberScalarWhereWithAggregatesInput = {
  AND?: Prisma.SubscriberScalarWhereWithAggregatesInput | Prisma.SubscriberScalarWhereWithAggregatesInput[]
  OR?: Prisma.SubscriberScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SubscriberScalarWhereWithAggregatesInput | Prisma.SubscriberScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Subscriber"> | string
  email?: Prisma.StringWithAggregatesFilter<"Subscriber"> | string
  name?: Prisma.StringNullableWithAggregatesFilter<"Subscriber"> | string | null
  phone?: Prisma.StringNullableWithAggregatesFilter<"Subscriber"> | string | null
  whatsappOptIn?: Prisma.BoolWithAggregatesFilter<"Subscriber"> | boolean
  status?: Prisma.EnumSubscriberStatusWithAggregatesFilter<"Subscriber"> | $Enums.SubscriberStatus
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Subscriber"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Subscriber"> | Date | string
  unsubscribedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Subscriber"> | Date | string | null
  confirmToken?: Prisma.StringNullableWithAggregatesFilter<"Subscriber"> | string | null
  confirmSentAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Subscriber"> | Date | string | null
  meta?: Prisma.JsonNullableWithAggregatesFilter<"Subscriber">
}

export type SubscriberCreateInput = {
  id?: string
  email: string
  name?: string | null
  phone?: string | null
  whatsappOptIn?: boolean
  status?: $Enums.SubscriberStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  unsubscribedAt?: Date | string | null
  confirmToken?: string | null
  confirmSentAt?: Date | string | null
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  emailLogs?: Prisma.EmailLogCreateNestedManyWithoutSubscriberInput
}

export type SubscriberUncheckedCreateInput = {
  id?: string
  email: string
  name?: string | null
  phone?: string | null
  whatsappOptIn?: boolean
  status?: $Enums.SubscriberStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  unsubscribedAt?: Date | string | null
  confirmToken?: string | null
  confirmSentAt?: Date | string | null
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  emailLogs?: Prisma.EmailLogUncheckedCreateNestedManyWithoutSubscriberInput
}

export type SubscriberUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  whatsappOptIn?: Prisma.BoolFieldUpdateOperationsInput | boolean
  status?: Prisma.EnumSubscriberStatusFieldUpdateOperationsInput | $Enums.SubscriberStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  unsubscribedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confirmSentAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  emailLogs?: Prisma.EmailLogUpdateManyWithoutSubscriberNestedInput
}

export type SubscriberUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  whatsappOptIn?: Prisma.BoolFieldUpdateOperationsInput | boolean
  status?: Prisma.EnumSubscriberStatusFieldUpdateOperationsInput | $Enums.SubscriberStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  unsubscribedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confirmSentAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  emailLogs?: Prisma.EmailLogUncheckedUpdateManyWithoutSubscriberNestedInput
}

export type SubscriberCreateManyInput = {
  id?: string
  email: string
  name?: string | null
  phone?: string | null
  whatsappOptIn?: boolean
  status?: $Enums.SubscriberStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  unsubscribedAt?: Date | string | null
  confirmToken?: string | null
  confirmSentAt?: Date | string | null
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SubscriberUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  whatsappOptIn?: Prisma.BoolFieldUpdateOperationsInput | boolean
  status?: Prisma.EnumSubscriberStatusFieldUpdateOperationsInput | $Enums.SubscriberStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  unsubscribedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confirmSentAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SubscriberUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  whatsappOptIn?: Prisma.BoolFieldUpdateOperationsInput | boolean
  status?: Prisma.EnumSubscriberStatusFieldUpdateOperationsInput | $Enums.SubscriberStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  unsubscribedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confirmSentAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SubscriberCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  whatsappOptIn?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  unsubscribedAt?: Prisma.SortOrder
  confirmToken?: Prisma.SortOrder
  confirmSentAt?: Prisma.SortOrder
  meta?: Prisma.SortOrder
}

export type SubscriberMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  whatsappOptIn?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  unsubscribedAt?: Prisma.SortOrder
  confirmToken?: Prisma.SortOrder
  confirmSentAt?: Prisma.SortOrder
}

export type SubscriberMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  whatsappOptIn?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  unsubscribedAt?: Prisma.SortOrder
  confirmToken?: Prisma.SortOrder
  confirmSentAt?: Prisma.SortOrder
}

export type SubscriberScalarRelationFilter = {
  is?: Prisma.SubscriberWhereInput
  isNot?: Prisma.SubscriberWhereInput
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type EnumSubscriberStatusFieldUpdateOperationsInput = {
  set?: $Enums.SubscriberStatus
}

export type SubscriberCreateNestedOneWithoutEmailLogsInput = {
  create?: Prisma.XOR<Prisma.SubscriberCreateWithoutEmailLogsInput, Prisma.SubscriberUncheckedCreateWithoutEmailLogsInput>
  connectOrCreate?: Prisma.SubscriberCreateOrConnectWithoutEmailLogsInput
  connect?: Prisma.SubscriberWhereUniqueInput
}

export type SubscriberUpdateOneRequiredWithoutEmailLogsNestedInput = {
  create?: Prisma.XOR<Prisma.SubscriberCreateWithoutEmailLogsInput, Prisma.SubscriberUncheckedCreateWithoutEmailLogsInput>
  connectOrCreate?: Prisma.SubscriberCreateOrConnectWithoutEmailLogsInput
  upsert?: Prisma.SubscriberUpsertWithoutEmailLogsInput
  connect?: Prisma.SubscriberWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SubscriberUpdateToOneWithWhereWithoutEmailLogsInput, Prisma.SubscriberUpdateWithoutEmailLogsInput>, Prisma.SubscriberUncheckedUpdateWithoutEmailLogsInput>
}

export type SubscriberCreateWithoutEmailLogsInput = {
  id?: string
  email: string
  name?: string | null
  phone?: string | null
  whatsappOptIn?: boolean
  status?: $Enums.SubscriberStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  unsubscribedAt?: Date | string | null
  confirmToken?: string | null
  confirmSentAt?: Date | string | null
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SubscriberUncheckedCreateWithoutEmailLogsInput = {
  id?: string
  email: string
  name?: string | null
  phone?: string | null
  whatsappOptIn?: boolean
  status?: $Enums.SubscriberStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  unsubscribedAt?: Date | string | null
  confirmToken?: string | null
  confirmSentAt?: Date | string | null
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SubscriberCreateOrConnectWithoutEmailLogsInput = {
  where: Prisma.SubscriberWhereUniqueInput
  create: Prisma.XOR<Prisma.SubscriberCreateWithoutEmailLogsInput, Prisma.SubscriberUncheckedCreateWithoutEmailLogsInput>
}

export type SubscriberUpsertWithoutEmailLogsInput = {
  update: Prisma.XOR<Prisma.SubscriberUpdateWithoutEmailLogsInput, Prisma.SubscriberUncheckedUpdateWithoutEmailLogsInput>
  create: Prisma.XOR<Prisma.SubscriberCreateWithoutEmailLogsInput, Prisma.SubscriberUncheckedCreateWithoutEmailLogsInput>
  where?: Prisma.SubscriberWhereInput
}

export type SubscriberUpdateToOneWithWhereWithoutEmailLogsInput = {
  where?: Prisma.SubscriberWhereInput
  data: Prisma.XOR<Prisma.SubscriberUpdateWithoutEmailLogsInput, Prisma.SubscriberUncheckedUpdateWithoutEmailLogsInput>
}

export type SubscriberUpdateWithoutEmailLogsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  whatsappOptIn?: Prisma.BoolFieldUpdateOperationsInput | boolean
  status?: Prisma.EnumSubscriberStatusFieldUpdateOperationsInput | $Enums.SubscriberStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  unsubscribedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confirmSentAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SubscriberUncheckedUpdateWithoutEmailLogsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  whatsappOptIn?: Prisma.BoolFieldUpdateOperationsInput | boolean
  status?: Prisma.EnumSubscriberStatusFieldUpdateOperationsInput | $Enums.SubscriberStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  unsubscribedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confirmSentAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}


/**
 * Count Type SubscriberCountOutputType
 */

export type SubscriberCountOutputType = {
  emailLogs: number
}

export type SubscriberCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  emailLogs?: boolean | SubscriberCountOutputTypeCountEmailLogsArgs
}

/**
 * SubscriberCountOutputType without action
 */
export type SubscriberCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubscriberCountOutputType
   */
  select?: Prisma.SubscriberCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SubscriberCountOutputType without action
 */
export type SubscriberCountOutputTypeCountEmailLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmailLogWhereInput
}


export type SubscriberSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  name?: boolean
  phone?: boolean
  whatsappOptIn?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  unsubscribedAt?: boolean
  confirmToken?: boolean
  confirmSentAt?: boolean
  meta?: boolean
  emailLogs?: boolean | Prisma.Subscriber$emailLogsArgs<ExtArgs>
  _count?: boolean | Prisma.SubscriberCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["subscriber"]>

export type SubscriberSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  name?: boolean
  phone?: boolean
  whatsappOptIn?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  unsubscribedAt?: boolean
  confirmToken?: boolean
  confirmSentAt?: boolean
  meta?: boolean
}, ExtArgs["result"]["subscriber"]>

export type SubscriberSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  name?: boolean
  phone?: boolean
  whatsappOptIn?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  unsubscribedAt?: boolean
  confirmToken?: boolean
  confirmSentAt?: boolean
  meta?: boolean
}, ExtArgs["result"]["subscriber"]>

export type SubscriberSelectScalar = {
  id?: boolean
  email?: boolean
  name?: boolean
  phone?: boolean
  whatsappOptIn?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  unsubscribedAt?: boolean
  confirmToken?: boolean
  confirmSentAt?: boolean
  meta?: boolean
}

export type SubscriberOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "email" | "name" | "phone" | "whatsappOptIn" | "status" | "createdAt" | "updatedAt" | "unsubscribedAt" | "confirmToken" | "confirmSentAt" | "meta", ExtArgs["result"]["subscriber"]>
export type SubscriberInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  emailLogs?: boolean | Prisma.Subscriber$emailLogsArgs<ExtArgs>
  _count?: boolean | Prisma.SubscriberCountOutputTypeDefaultArgs<ExtArgs>
}
export type SubscriberIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type SubscriberIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $SubscriberPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Subscriber"
  objects: {
    emailLogs: Prisma.$EmailLogPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    email: string
    name: string | null
    /**
     * E.164 format; optional. When set, unique across subscribers. Used for WhatsApp notifications when whatsappOptIn is true.
     */
    phone: string | null
    /**
     * If true and phone is set, subscriber receives WhatsApp notifications for new newsletters. Default false for migration safety and explicit opt-in.
     */
    whatsappOptIn: boolean
    status: $Enums.SubscriberStatus
    createdAt: Date
    updatedAt: Date
    unsubscribedAt: Date | null
    /**
     * When set, the subscriber has not yet confirmed their email. Token is sent in confirmation link.
     */
    confirmToken: string | null
    /**
     * Timestamp when the double opt-in confirmation email was sent.
     */
    confirmSentAt: Date | null
    /**
     * Arbitrary metadata such as source, custom tags, etc.
     */
    meta: runtime.JsonValue | null
  }, ExtArgs["result"]["subscriber"]>
  composites: {}
}

export type SubscriberGetPayload<S extends boolean | null | undefined | SubscriberDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SubscriberPayload, S>

export type SubscriberCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SubscriberFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SubscriberCountAggregateInputType | true
  }

export interface SubscriberDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Subscriber'], meta: { name: 'Subscriber' } }
  /**
   * Find zero or one Subscriber that matches the filter.
   * @param {SubscriberFindUniqueArgs} args - Arguments to find a Subscriber
   * @example
   * // Get one Subscriber
   * const subscriber = await prisma.subscriber.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SubscriberFindUniqueArgs>(args: Prisma.SelectSubset<T, SubscriberFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SubscriberClient<runtime.Types.Result.GetResult<Prisma.$SubscriberPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Subscriber that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SubscriberFindUniqueOrThrowArgs} args - Arguments to find a Subscriber
   * @example
   * // Get one Subscriber
   * const subscriber = await prisma.subscriber.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SubscriberFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SubscriberFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SubscriberClient<runtime.Types.Result.GetResult<Prisma.$SubscriberPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Subscriber that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubscriberFindFirstArgs} args - Arguments to find a Subscriber
   * @example
   * // Get one Subscriber
   * const subscriber = await prisma.subscriber.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SubscriberFindFirstArgs>(args?: Prisma.SelectSubset<T, SubscriberFindFirstArgs<ExtArgs>>): Prisma.Prisma__SubscriberClient<runtime.Types.Result.GetResult<Prisma.$SubscriberPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Subscriber that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubscriberFindFirstOrThrowArgs} args - Arguments to find a Subscriber
   * @example
   * // Get one Subscriber
   * const subscriber = await prisma.subscriber.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SubscriberFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SubscriberFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SubscriberClient<runtime.Types.Result.GetResult<Prisma.$SubscriberPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Subscribers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubscriberFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Subscribers
   * const subscribers = await prisma.subscriber.findMany()
   * 
   * // Get first 10 Subscribers
   * const subscribers = await prisma.subscriber.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const subscriberWithIdOnly = await prisma.subscriber.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SubscriberFindManyArgs>(args?: Prisma.SelectSubset<T, SubscriberFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubscriberPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Subscriber.
   * @param {SubscriberCreateArgs} args - Arguments to create a Subscriber.
   * @example
   * // Create one Subscriber
   * const Subscriber = await prisma.subscriber.create({
   *   data: {
   *     // ... data to create a Subscriber
   *   }
   * })
   * 
   */
  create<T extends SubscriberCreateArgs>(args: Prisma.SelectSubset<T, SubscriberCreateArgs<ExtArgs>>): Prisma.Prisma__SubscriberClient<runtime.Types.Result.GetResult<Prisma.$SubscriberPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Subscribers.
   * @param {SubscriberCreateManyArgs} args - Arguments to create many Subscribers.
   * @example
   * // Create many Subscribers
   * const subscriber = await prisma.subscriber.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SubscriberCreateManyArgs>(args?: Prisma.SelectSubset<T, SubscriberCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Subscribers and returns the data saved in the database.
   * @param {SubscriberCreateManyAndReturnArgs} args - Arguments to create many Subscribers.
   * @example
   * // Create many Subscribers
   * const subscriber = await prisma.subscriber.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Subscribers and only return the `id`
   * const subscriberWithIdOnly = await prisma.subscriber.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SubscriberCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SubscriberCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubscriberPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Subscriber.
   * @param {SubscriberDeleteArgs} args - Arguments to delete one Subscriber.
   * @example
   * // Delete one Subscriber
   * const Subscriber = await prisma.subscriber.delete({
   *   where: {
   *     // ... filter to delete one Subscriber
   *   }
   * })
   * 
   */
  delete<T extends SubscriberDeleteArgs>(args: Prisma.SelectSubset<T, SubscriberDeleteArgs<ExtArgs>>): Prisma.Prisma__SubscriberClient<runtime.Types.Result.GetResult<Prisma.$SubscriberPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Subscriber.
   * @param {SubscriberUpdateArgs} args - Arguments to update one Subscriber.
   * @example
   * // Update one Subscriber
   * const subscriber = await prisma.subscriber.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SubscriberUpdateArgs>(args: Prisma.SelectSubset<T, SubscriberUpdateArgs<ExtArgs>>): Prisma.Prisma__SubscriberClient<runtime.Types.Result.GetResult<Prisma.$SubscriberPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Subscribers.
   * @param {SubscriberDeleteManyArgs} args - Arguments to filter Subscribers to delete.
   * @example
   * // Delete a few Subscribers
   * const { count } = await prisma.subscriber.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SubscriberDeleteManyArgs>(args?: Prisma.SelectSubset<T, SubscriberDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Subscribers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubscriberUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Subscribers
   * const subscriber = await prisma.subscriber.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SubscriberUpdateManyArgs>(args: Prisma.SelectSubset<T, SubscriberUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Subscribers and returns the data updated in the database.
   * @param {SubscriberUpdateManyAndReturnArgs} args - Arguments to update many Subscribers.
   * @example
   * // Update many Subscribers
   * const subscriber = await prisma.subscriber.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Subscribers and only return the `id`
   * const subscriberWithIdOnly = await prisma.subscriber.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SubscriberUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SubscriberUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubscriberPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Subscriber.
   * @param {SubscriberUpsertArgs} args - Arguments to update or create a Subscriber.
   * @example
   * // Update or create a Subscriber
   * const subscriber = await prisma.subscriber.upsert({
   *   create: {
   *     // ... data to create a Subscriber
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Subscriber we want to update
   *   }
   * })
   */
  upsert<T extends SubscriberUpsertArgs>(args: Prisma.SelectSubset<T, SubscriberUpsertArgs<ExtArgs>>): Prisma.Prisma__SubscriberClient<runtime.Types.Result.GetResult<Prisma.$SubscriberPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Subscribers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubscriberCountArgs} args - Arguments to filter Subscribers to count.
   * @example
   * // Count the number of Subscribers
   * const count = await prisma.subscriber.count({
   *   where: {
   *     // ... the filter for the Subscribers we want to count
   *   }
   * })
  **/
  count<T extends SubscriberCountArgs>(
    args?: Prisma.Subset<T, SubscriberCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SubscriberCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Subscriber.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubscriberAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SubscriberAggregateArgs>(args: Prisma.Subset<T, SubscriberAggregateArgs>): Prisma.PrismaPromise<GetSubscriberAggregateType<T>>

  /**
   * Group by Subscriber.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubscriberGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SubscriberGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SubscriberGroupByArgs['orderBy'] }
      : { orderBy?: SubscriberGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SubscriberGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSubscriberGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Subscriber model
 */
readonly fields: SubscriberFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Subscriber.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SubscriberClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  emailLogs<T extends Prisma.Subscriber$emailLogsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Subscriber$emailLogsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmailLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Subscriber model
 */
export interface SubscriberFieldRefs {
  readonly id: Prisma.FieldRef<"Subscriber", 'String'>
  readonly email: Prisma.FieldRef<"Subscriber", 'String'>
  readonly name: Prisma.FieldRef<"Subscriber", 'String'>
  readonly phone: Prisma.FieldRef<"Subscriber", 'String'>
  readonly whatsappOptIn: Prisma.FieldRef<"Subscriber", 'Boolean'>
  readonly status: Prisma.FieldRef<"Subscriber", 'SubscriberStatus'>
  readonly createdAt: Prisma.FieldRef<"Subscriber", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Subscriber", 'DateTime'>
  readonly unsubscribedAt: Prisma.FieldRef<"Subscriber", 'DateTime'>
  readonly confirmToken: Prisma.FieldRef<"Subscriber", 'String'>
  readonly confirmSentAt: Prisma.FieldRef<"Subscriber", 'DateTime'>
  readonly meta: Prisma.FieldRef<"Subscriber", 'Json'>
}
    

// Custom InputTypes
/**
 * Subscriber findUnique
 */
export type SubscriberFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subscriber
   */
  select?: Prisma.SubscriberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subscriber
   */
  omit?: Prisma.SubscriberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriberInclude<ExtArgs> | null
  /**
   * Filter, which Subscriber to fetch.
   */
  where: Prisma.SubscriberWhereUniqueInput
}

/**
 * Subscriber findUniqueOrThrow
 */
export type SubscriberFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subscriber
   */
  select?: Prisma.SubscriberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subscriber
   */
  omit?: Prisma.SubscriberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriberInclude<ExtArgs> | null
  /**
   * Filter, which Subscriber to fetch.
   */
  where: Prisma.SubscriberWhereUniqueInput
}

/**
 * Subscriber findFirst
 */
export type SubscriberFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subscriber
   */
  select?: Prisma.SubscriberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subscriber
   */
  omit?: Prisma.SubscriberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriberInclude<ExtArgs> | null
  /**
   * Filter, which Subscriber to fetch.
   */
  where?: Prisma.SubscriberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Subscribers to fetch.
   */
  orderBy?: Prisma.SubscriberOrderByWithRelationInput | Prisma.SubscriberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Subscribers.
   */
  cursor?: Prisma.SubscriberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Subscribers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Subscribers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Subscribers.
   */
  distinct?: Prisma.SubscriberScalarFieldEnum | Prisma.SubscriberScalarFieldEnum[]
}

/**
 * Subscriber findFirstOrThrow
 */
export type SubscriberFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subscriber
   */
  select?: Prisma.SubscriberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subscriber
   */
  omit?: Prisma.SubscriberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriberInclude<ExtArgs> | null
  /**
   * Filter, which Subscriber to fetch.
   */
  where?: Prisma.SubscriberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Subscribers to fetch.
   */
  orderBy?: Prisma.SubscriberOrderByWithRelationInput | Prisma.SubscriberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Subscribers.
   */
  cursor?: Prisma.SubscriberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Subscribers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Subscribers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Subscribers.
   */
  distinct?: Prisma.SubscriberScalarFieldEnum | Prisma.SubscriberScalarFieldEnum[]
}

/**
 * Subscriber findMany
 */
export type SubscriberFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subscriber
   */
  select?: Prisma.SubscriberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subscriber
   */
  omit?: Prisma.SubscriberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriberInclude<ExtArgs> | null
  /**
   * Filter, which Subscribers to fetch.
   */
  where?: Prisma.SubscriberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Subscribers to fetch.
   */
  orderBy?: Prisma.SubscriberOrderByWithRelationInput | Prisma.SubscriberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Subscribers.
   */
  cursor?: Prisma.SubscriberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Subscribers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Subscribers.
   */
  skip?: number
  distinct?: Prisma.SubscriberScalarFieldEnum | Prisma.SubscriberScalarFieldEnum[]
}

/**
 * Subscriber create
 */
export type SubscriberCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subscriber
   */
  select?: Prisma.SubscriberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subscriber
   */
  omit?: Prisma.SubscriberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriberInclude<ExtArgs> | null
  /**
   * The data needed to create a Subscriber.
   */
  data: Prisma.XOR<Prisma.SubscriberCreateInput, Prisma.SubscriberUncheckedCreateInput>
}

/**
 * Subscriber createMany
 */
export type SubscriberCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Subscribers.
   */
  data: Prisma.SubscriberCreateManyInput | Prisma.SubscriberCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Subscriber createManyAndReturn
 */
export type SubscriberCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subscriber
   */
  select?: Prisma.SubscriberSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Subscriber
   */
  omit?: Prisma.SubscriberOmit<ExtArgs> | null
  /**
   * The data used to create many Subscribers.
   */
  data: Prisma.SubscriberCreateManyInput | Prisma.SubscriberCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Subscriber update
 */
export type SubscriberUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subscriber
   */
  select?: Prisma.SubscriberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subscriber
   */
  omit?: Prisma.SubscriberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriberInclude<ExtArgs> | null
  /**
   * The data needed to update a Subscriber.
   */
  data: Prisma.XOR<Prisma.SubscriberUpdateInput, Prisma.SubscriberUncheckedUpdateInput>
  /**
   * Choose, which Subscriber to update.
   */
  where: Prisma.SubscriberWhereUniqueInput
}

/**
 * Subscriber updateMany
 */
export type SubscriberUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Subscribers.
   */
  data: Prisma.XOR<Prisma.SubscriberUpdateManyMutationInput, Prisma.SubscriberUncheckedUpdateManyInput>
  /**
   * Filter which Subscribers to update
   */
  where?: Prisma.SubscriberWhereInput
  /**
   * Limit how many Subscribers to update.
   */
  limit?: number
}

/**
 * Subscriber updateManyAndReturn
 */
export type SubscriberUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subscriber
   */
  select?: Prisma.SubscriberSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Subscriber
   */
  omit?: Prisma.SubscriberOmit<ExtArgs> | null
  /**
   * The data used to update Subscribers.
   */
  data: Prisma.XOR<Prisma.SubscriberUpdateManyMutationInput, Prisma.SubscriberUncheckedUpdateManyInput>
  /**
   * Filter which Subscribers to update
   */
  where?: Prisma.SubscriberWhereInput
  /**
   * Limit how many Subscribers to update.
   */
  limit?: number
}

/**
 * Subscriber upsert
 */
export type SubscriberUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subscriber
   */
  select?: Prisma.SubscriberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subscriber
   */
  omit?: Prisma.SubscriberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriberInclude<ExtArgs> | null
  /**
   * The filter to search for the Subscriber to update in case it exists.
   */
  where: Prisma.SubscriberWhereUniqueInput
  /**
   * In case the Subscriber found by the `where` argument doesn't exist, create a new Subscriber with this data.
   */
  create: Prisma.XOR<Prisma.SubscriberCreateInput, Prisma.SubscriberUncheckedCreateInput>
  /**
   * In case the Subscriber was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SubscriberUpdateInput, Prisma.SubscriberUncheckedUpdateInput>
}

/**
 * Subscriber delete
 */
export type SubscriberDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subscriber
   */
  select?: Prisma.SubscriberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subscriber
   */
  omit?: Prisma.SubscriberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriberInclude<ExtArgs> | null
  /**
   * Filter which Subscriber to delete.
   */
  where: Prisma.SubscriberWhereUniqueInput
}

/**
 * Subscriber deleteMany
 */
export type SubscriberDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Subscribers to delete
   */
  where?: Prisma.SubscriberWhereInput
  /**
   * Limit how many Subscribers to delete.
   */
  limit?: number
}

/**
 * Subscriber.emailLogs
 */
export type Subscriber$emailLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailLog
   */
  select?: Prisma.EmailLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailLog
   */
  omit?: Prisma.EmailLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailLogInclude<ExtArgs> | null
  where?: Prisma.EmailLogWhereInput
  orderBy?: Prisma.EmailLogOrderByWithRelationInput | Prisma.EmailLogOrderByWithRelationInput[]
  cursor?: Prisma.EmailLogWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EmailLogScalarFieldEnum | Prisma.EmailLogScalarFieldEnum[]
}

/**
 * Subscriber without action
 */
export type SubscriberDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subscriber
   */
  select?: Prisma.SubscriberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subscriber
   */
  omit?: Prisma.SubscriberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriberInclude<ExtArgs> | null
}
